### ISSUE TITLE
Half pie chart

### ISSUE THREAD

**Issue by goldenivan** [airbnb/visx#1006]
Hi,

I am trying to draw a half pie chart. I tried using  **startAngle**, set to **-90** and **endAngle**, set to **90**. I would like this kind of result : 

https://datavizproject.com/wp-content/uploads/2016/06/DVP_1_100-76.png

Is it possible with Visx ?

Regards,

**Comment by RIP21** [comment]
BTW, I think it's more a question than the issue, so this should go to the Discussion section I think :) (check above)

**Comment by goldenivan** [comment]
Hello,

That's right, I will do it. I close this one.
