### ISSUE TITLE
[xy-chart] When hover over tooltips in StrictMode there is an error: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by RIP21** [airbnb/visx#1009]
Using XyChart in the StrictMode I'm getting this error into the console (it doesn't break app, but just bloats it). Will be nice to fix :)
```
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of withBoundingRects() which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```
It only happens when you hover over tooltips.
So if you go to XYChart demo on Codesandbox wrap the whole app in React.StrictMode and then hover over the graph it will be complaining in the console.

**Comment by williaster** [comment]
Going to close this as it duplicates #737

**Comment by RIP21** [comment]
Oops. Sorry :) I searched by haven't found :) Probably wrong query :P
