### ISSUE TITLE
[xy-chart] Forward ref

### ISSUE THREAD

**Issue by valtism** [airbnb/visx#1023]
Would be useful to be able to attach a ref to the `<XYChart>` component via a [forwarded ref](https://reactjs.org/docs/forwarding-refs.html).

Any issues with this?

**Comment by williaster** [comment]
No issues as far as I see, we've added these as requested to other components. I'm pretty slammed right now but happy to review a PR! 👀 

Out of curiosity can you share the use case you have for this?

**Comment by valtism** [comment]
Apologies, I figured out I don't have this use-case.
