### ISSUE TITLE
rollup error on importing @visx/text

### ISSUE THREAD

**Issue by merrymaker14** [airbnb/visx#1029]
I'm sure that's becouse of there lines:

https://github.com/airbnb/visx/blob/master/packages/visx-text/src/Text.tsx#L3
https://github.com/airbnb/visx/blob/master/packages/visx-text/src/Text.tsx#L5

**Comment by williaster** [comment]
Hey @merrymaker14 thanks for checking out `visx`. I think this isn't an issue with `visx`, it's an issue with rollup. Seems like it's discussed at length in [this issue](https://github.com/rollup/rollup-plugin-typescript/issues/28). 

Going to close for now but feel free to re-open if you think it is a `visx` problem.
