### ISSUE TITLE
Issue with keys in XY Chart

### ISSUE THREAD

**Issue by ShaneHudson** [airbnb/visx#1038]
This issue seems closely related to #969, I considered commenting there but as it is closed have opened a new ticket.

I have three XYCharts on the same page next to each other. They work fine but am getting warnings a lot:

```
index.js:1 Warning: Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behaviour is unsupported and could change in a future version.
    in AnimatedGridLines (created by GridRows)
    in g (created by Group)
    in Group (created by GridRows)
    in GridRows (created by AnimatedGridRows)
    in AnimatedGridRows
    in Unknown (created by BaseGrid)
    in BaseGrid (created by AnimatedGrid)
    in AnimatedGrid (at Graph.js:89)
    in svg (created by XYChart)
    in XYChart (created by XYChart)
```

All of the components I'm using directly have `key` (even those that may not require it) and `AnimatedLineSeries` and `GlpyhSeries` both also have `dataKey`. These are all unique and uses a string passed through to each graph so each are different.

It appears that the keys are clashing further down?

Could you take a look please? Cheers!

**Comment by ShaneHudson** [comment]
Using the non-animated version seems to fix this.

**Comment by williaster** [comment]
Thanks for reporting this, I think this comes from `AnimatedScale` in `@visx/react-spring`. I'll try to take a look this week 👀

**Comment by williaster** [comment]
@ShaneHudson can you link to a sandbox which reproduces this?

**Comment by williaster** [comment]
Going to close this for now as I can't repro/no sandbox was ever provided.
