### ISSUE TITLE
[visx/visx] namespace all exports 

### ISSUE THREAD

**Issue by williaster** [airbnb/visx#1047]
#1043 name-spaced the `@visx/xychart` package from `@visx/visx` to an `XYChart` variable to avoid name conflicts between package exports.

For `2.0.0` we could make this consistent for all packages.

**Comment by robsutcliffe** [comment]
@williaster I'd be willing to help as a beginner

To clarify: the plan is for [all packages exported here](https://github.com/airbnb/visx/blob/master/packages/visx-visx/src/index.ts) to be exported using the package name as a namespace. so for example Annotation would be imported like:
`import { Annotation } from '@visx/visx';`

and then used like:
`<Annotation.LineSubject />`

**Comment by williaster** [comment]
hey @robsutcliffe 👋 , awesome! 

yes, you're correct about the plan and the API 💯  We did this initially with the `@visx/xychart` package, and as you can see in the `index` file you linked to we used `XYChartPackage` for the exported name. I think ideally we don't include `*Package` in the export name, your example of `Annotation` is could be used across all packages (e.g., `XYChartPackage` could be updated to `XYChart`).

**Comment by robsutcliffe** [comment]
Great. Feel free to assign this to me and I'll add a PR soon

**Comment by williaster** [comment]
closed by #1121
