### ISSUE TITLE
BarStack, SeriesPoint in JS

### ISSUE THREAD

**Issue by libnine** [airbnb/visx#1053]
I'm having a bit of trouble converting the [BarStack example](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-barstack?file=/Example.tsx) into JS. Firstly, I'm not entirely sure where to implement `SeriesPoint` and I seem to be getting a lot of Negative value errors in `rect`:

![image](https://user-images.githubusercontent.com/31510420/107305940-c6be3880-6a38-11eb-9d60-20087c5ec338.png)

Here's my sandbox: https://codesandbox.io/s/admiring-proskuriakova-qnkko?file=/src/App.js

**Comment by williaster** [comment]
Hey @libnine you were not setting a `range` on your scales which means that they rendered into zero width height. In addition you were using a mix of random offsets, `margin` and `defaultMargin` which made the graph dimensions all wrong once the `range` was set.

Your tooltip data types are also all inconsistent / invalid, I fixed them so they at least don't throw errors.

Here's a working [sandbox](https://codesandbox.io/s/hopeful-khayyam-dsv4u?file=/src/App.js).

**Comment by williaster** [comment]
You might also consider using our github discussions in the future since this is not a library issue, it's a usage issue.

**Comment by libnine** [comment]
Thanks a bunch @williaster.. didn't know about the discussions - will do!

**Comment by jimmy-e** [comment]
@williaster , how would you rotate your working sandbox to be horizontal?
