### ISSUE TITLE
Missing exports in mock-data ?

### ISSUE THREAD

**Issue by LoiKos** [airbnb/visx#1058]
Hi there ! I'm trying to create some stats chart looking at this example https://airbnb.io/visx/statsplot.

But unfortunately when i'm trying to use these imports : 
`import { getSeededRandom, getRandomNormal } from '@visx/mock-data'`

i get an error :
<img width="1156" alt="Capture d’écran 2021-02-10 à 16 25 09" src="https://user-images.githubusercontent.com/9548473/107530866-8d163a80-6bbc-11eb-9ea6-729e8d3a8551.png">

Sandbox : https://codesandbox.io/s/summer-dawn-eezwj?file=/src/App.js

Is there some exports missing or is this intended API changes ? If it's intended i believe you should add docs about it

**Comment by williaster** [comment]
Hey @LoiKos 👋  thanks for checking out `visx`. These functions were added in #1033 and will be released in `1.5.0`. I should be able to get that out today and will close this then.

**Comment by LoiKos** [comment]
Thank you for your quick answer 👍  I will looking to these changes when `1.5.0` is out thanks :)

I just add 2 suggestions that makes `genStats` maybe easier to use 

1.  xAxis customization

```js
// today 
  const boxPlot = {
      x: `${xAxis(i)}`,
      ...
      }
// idea
function genStats(
  number,
  random = defaultRandom,
  randomOffset = defaultRandomOffset,
  xAxis = (i) => `Statistics ${i}`
) {
...
  const boxPlot = {
      x: xAxis(i),
      ...
      }
   ...
   }
```
2.  I don't know if you are looking into this but i build a boxPlots based 12 month. So it's great to be able to generate boxPlots for each month directly but unfortunately you don't get the original data (only bin) for each month so user are not able to calculate for example yearly mean/median. I think it could be a great addition to `genStats`.  There is multiple options to add this functionality so if you are interested i could give you some examples 😄

**Comment by williaster** [comment]
Hey @LoiKos `1.5.0` is out now. These are good suggestions for `genStats` 👍  I'm not sure I'll have bandwidth to take this on soon but I would happily review a PR.

I'm going to update the issue title to reflect the feature request + add the help-wanted tag 😄

**Comment by williaster** [comment]
actually, let's close this issue and open a new one for the feature request :)
