### ISSUE TITLE
Add "easy to get started with" examples

### ISSUE THREAD

**Issue by chris-aeviator** [airbnb/visx#1061]
While I appreciate the "showoff" gallery I can see very fast that this library requires serious understanding of many concepts. It is indeed beautiful and technically clean, but not friendly to beginners at all. It uses many concepts that might show how cool one can work with JS/TypeScript but also feels a bit like someone wanted to show off their coding skills to me.  

As a user I want to get started fast and not go through references of 5 modules to understand how to build a single line graph..instead of 5 linegraphs and data coming in from another package that then mocks it , why not concentrate on teaching howto use this library like you do with the 1(!) example in readme.md on a close to real life usecase.

This is not meant to overly criticise the creators here, I'm just trying to make clear that a lot of people will have a hard time and spend days on learning how to use this library if not prior experienced developers, since the outcome indeed can look pretty amazing.

**Comment by akshay-nm** [comment]
Where's the `AreaChart` component in [https://vx-demo.vercel.app/brush](https://vx-demo.vercel.app/brush)?

**Comment by chris-aeviator** [comment]
@akshay-nm https://github.com/airbnb/visx/blob/master/packages/visx-demo/src/sandboxes/visx-brush/AreaChart.tsx

**Comment by akshay-nm** [comment]
Is there a difference between `@visx` and `@vx`?

**Comment by chris-aeviator** [comment]
Looking at the version history of both `@vx` seems to be a old/legacy package

![image](https://user-images.githubusercontent.com/11522213/115545288-ed53e780-a2a3-11eb-909a-602486078b6f.png)
![image](https://user-images.githubusercontent.com/11522213/115545325-f80e7c80-a2a3-11eb-93d6-5d83163fdc8a.png)

**Comment by akshay-nm** [comment]
Thanks man! I just realized I was stuck on the old website. :/ 
My bad. 
I'll try to stick to the new one! which is https://airbnb.io/visx/

**Comment by williaster** [comment]
Sorry y'all, we should take down the legacy `@vx` demo site 🤦  I'll create an issue to track this. To clarify: `vx` was the pre-`1.0` version of this project before it was moved into the airbnb github.

As far as simple gallery examples, I totally get it. I'd be happy to review simpler additions if anyone wants to add any! These should follow the current codesandbox format, and we may make requests to keep example aesthetics high in quality. 🙏 ✨

**Comment by hshoff** [comment]
Thanks for the feedback and thanks for checking out visx. Going to close this for now, but we're happy to review any PRs.
