### ISSUE TITLE
[XYChart] onPointerUp fires twice

### ISSUE THREAD

**Issue by valtism** [airbnb/visx#1077]
**Steps to reproduce:**
1. Go to https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-xychart?file=/Example.tsx
2. Add a `console.log` to the `onPointerUp` handler
3. Open the console and click on the chart area

**Expected output:**
`console.log` outputs a single line

**Output:**
`console.log` is fired twice

Not sure where this is coming from, but `useEventHandlers` is being called twice.

**Comment by williaster** [comment]
Hey @valtism 👋 . Thanks for reporting this one! 🙏 

I'll try to take a look early this week 👀 .
