### ISSUE TITLE
visx/gradient peerDependency error with React 17.0.1

### ISSUE THREAD

**Issue by nicolas-macias** [airbnb/visx#1090]
https://github.com/airbnb/visx/blob/0c41229bef49427abb199a351ca000ea7c662fba/packages/visx-gradient/package.json#L35

When installing this library into a React 17 application, npm error comes up:

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0-0 || ^16.0.0-0" from @visx/gradient@1.0.0
npm ERR! node_modules/@visx/gradient
npm ERR!   @visx/gradient@"^1.0.0" from the root project
```

Same issue comes up when installing @visx/shape

**Comment by hshoff** [comment]
Hi @nicolas-macias, thanks for reporting. 

We're tracking progress to add React 17 support here: https://github.com/airbnb/visx/issues/872
