### ISSUE TITLE
[tooltip][annotation] update react-use-measure dep

### ISSUE THREAD

**Issue by hshoff** [airbnb/visx#1091]
There's an issue with `react-use-measure` causing problems with cjs exports as described here: https://github.com/grafana/grafana/issues/31598 and there's a PR to fix here: https://github.com/pmndrs/react-use-measure/pull/38

This issue is to track the `react-use-measure` change. If it blocks too long we should explore dropping the dep and going forward with an api compatible fix. 

cc @williaster

**Comment by mckn** [comment]
An alternative would be to use this function: https://github.com/streamich/react-use/blob/master/docs/useMeasure.md

**Comment by hshoff** [comment]
An audit of deps shows `react-use-measure` is a [dep of](https://github.com/airbnb/visx/search?q=react-use-measure) `@visx/tooltip` and `@visx/annotation`. `@visx/xy-chart` uses it through tooltip and need to be checked as well to verify api compatible replacement. 

Will take a look to scope out the work needed to replace `react-use-measure` with `react-use/useMeasure`

cc @williaster

**Comment by hshoff** [comment]
Reached out to drcmda and he was quick to merge the PR to fix in `react-use-measure`: https://github.com/pmndrs/react-use-measure/pull/38 and published in `react-use-measure@2.0.4`.

Changing the issue to bump version dep in visx.
