### ISSUE TITLE
[brush] Drag ends when mouse leaves the BrushHandle

### ISSUE THREAD

**Issue by Atralbus** [airbnb/visx#1109]
When we create a new brush `rect`, we can move the mouse outside the brush area while dragging. If we don't trigger `mouseup` we can move the mouse back in to the brush area to continue dragging. But when we trigger a drag from `BrushHandle` and move mouse outside the brush area it immediately triggers `dragEnd` which prevents us to continue brushing by moving mouse inside the brush area.

1. Go to https://airbnb.io/visx/brush.
2. Drag the brush from left or right handle and move mouse outside the brush area.
3. Move back mouse inside the brush area while holding left mouse button.
4. See that brush no longer moves.

I think we should be able to move brush even if the mouse leaves the brush area or handle.

Correct behavior in `BaseBrush`
![Screen Recording 2021-03-15 at 15 40 35](https://user-images.githubusercontent.com/4368872/111155433-82790780-85a5-11eb-94b5-9b45ee9ded7a.gif)

The problem with `BrushHandle`
![Screen Recording 2021-03-15 at 15 40 20](https://user-images.githubusercontent.com/4368872/111155441-84db6180-85a5-11eb-805c-f00d9ff04fff.gif)

This is a minor issue with the user experience of `Brush` component. But there seems to be a bigger problem. Currently, the component cannot catch up with fast mouse move events, if you move mouse outside the brush area too fast, it will leave the brush a bit far from the edge of the brush area. If you check this d3 [demo](https://bl.ocks.org/bumbeishvili/6c54d3f0e202aa7004a669a768369c5d) you can see that no matter how fast you move mouse outside, it stops on the edge of the brush area. This greatly improves the user experience with the component. Here's the fast drag issue;

![Screen Recording 2021-03-15 at 16 06 43](https://user-images.githubusercontent.com/4368872/111158008-9b36ec80-85a8-11eb-815b-fe4e133c3447.gif)

Thank you for this great library. It makes it a lot easier to create complex charts in React. Hoping to see more.

**Comment by williaster** [comment]
closed by #1164
