### ISSUE TITLE
AnimatedGridLines issue with React-spring 9.0.0

### ISSUE THREAD

**Issue by DanielHuntleySBG** [airbnb/visx#1122]
**Issue:**
Upgrading to the latest React-spring version (9.0.0) causes issues with the animated components.

**Error:** 
Cannot read property 'fromX' of undefined (AnimatedGridLines.js:29)

**Example Sandbox:**
https://codesandbox.io/s/runtime-monad-orc12

**Comment by achhunna** [comment]
Having the same issue as well. Any idea what the solution is?

**Comment by williaster** [comment]
`react-spring@9` had a ton of breaking changes so I think we'll need to update the relevant `@visx/*` packages to `9` and probably release `2.0.0` `@visx` versions. I don't think there's a way to have compatibility with both `8` & `9` unfortunately.

**Comment by joernroeder** [comment]
would love to see v9 support as well

**Comment by williaster** [comment]
Note this is released in `v2.0.0-alpha.0`, we are trying to lump the `react-17` upgrade into the `2.0.0` release as well hence the `alpha`.
