### ISSUE TITLE
Bad label position @visx/annotation

### ISSUE THREAD

**Issue by vovakulikov** [airbnb/visx#1126]
Hi there! 

I found interesting bug in label positioning.

Label component from @visx/annotation is trying to calculate right position for text according `x`, `y`, `dx` and `dy` props. But this component does’t take into account real width of text element. Instead of it that component set some default value for width prop. Also this component doesn't consider paddings value to calculate a right value of text width.

Because of that sometime we have strange visual behavior of labels (see screenshot below - example with Pie chart). Pay attention to Firefox and Safari labels position. 

**Actual behaviour**

<img src="https://user-images.githubusercontent.com/18492575/112897860-cd883400-90e8-11eb-9d81-d32e555b9346.jpg" width="500" >

See next image and take a look at Firefox label. Text anchor and translation of text were applied according 
`dx` and `dy` props values.

**Expected behaviour**

<img src="https://user-images.githubusercontent.com/18492575/112897900-da0c8c80-90e8-11eb-87c0-a5fbec9b3f9d.jpg " width="500" >

You can reproduce this bug here 
**Codesandbox** Bad label positioning example 
https://codesandbox.io/s/bold-antonelli-0v17h?file=/src/pie-chart.tsx

**GitHub repo branch** 
https://github.com/vovakulikov/chart-grid-sandbox/tree/bad-label-positioning-example

**Comment by WongyuChoi** [comment]
Any updates on this?  I am also having the same issue with label positioning at Firefox and Safari.
