### ISSUE TITLE
Question around animation performance

### ISSUE THREAD

**Issue by aulneau** [airbnb/visx#1142]
Hi there!

First off, thanks for an amazing library. I've been a long time follower and happy user :)

I am using the xychart component, and I really love how it abstracts away a lot of the complexity around building out charts with all the other packages. I have it working really well, outside of a small glitch in the animations when changing between different sets of data.

The issue i am having is that when I click a button to change the data source, the chart animates, but before it animates, it seems to switch to a different value before it can smoothly animate to the new value.

At first I thought there was something up with my state setter, maybe it was firing more than once, causing many re-renders, etc. But I have everything memo'ed and callback'ed, and a really fine control over all the rendering. Even using rafz to batch updates (this happens with or without requestAnimationFrame).

I'm curious if this has been seen before and if so, what can I do about it?

https://user-images.githubusercontent.com/11803153/113793553-30438600-970e-11eb-8363-de7d24d68425.mp4

**Comment by williaster** [comment]
Hey @aulneau thanks for the kind words and sharing this issue 🙏  Do you happen to have a codesandbox version to introspect / play around with the code? Things like this can be difficult to debug without knowing specific implementation details, especially since we don't see this behavior in the `xychart` demo example.

My guess is that it's not handling key changes or # data point changes well but would need to dig in further to reproduce.

**Comment by aulneau** [comment]
@williaster 

So in making the codesandbox, I determined 2 issues I had:

- had v9 of react-spring installed, that cause a majority of the choppy animations. Downgrading fixed that
- There were still some minor glitches, and when I updated my xScale and yScale away from:

```tsx
    const xMax = width;
    const yMax = height;
    const xDomain = useMemo(
      () => (xScale === 'time' ? extent(data, getXValue) : data.map(getXValue)),
      [data]
    );
    const yDomain = useMemo(
      () => [Math.min(...data.map(getYValue)), Math.max(...data.map(getYValue))],
      [data]
    );

// later in component

         <XYChart
          width={width}
          height={height}
          yScale={{
            type: 'log',
            range: [yMax, 0],
            round: false,
            domain: yDomain,
          }} // these seem to cause glitches in which value the animation is using
          xScale={{
            type: xScale !== 'time' ? 'point' : 'time',
            range: [0, xMax],
            round: false,
            domain: xDomain,
            padding: 0,
          }}
          margin={{ top: 0, right: 0, bottom: 0, left: 0 }}
        >
```
to
```tsx
         <XYChart
          width={width}
          height={height}
          yScale={{
            type: 'log',
          }}
          xScale={{
            type: 'time',
          }}
          margin={{ top: 0, right: 0, bottom: 0, left: 0 }}
        >
```

Everything works and is smooth like butter. Will close out, but feel free to comment with any thoughts/questions if you have any!
