### ISSUE TITLE
XYChart Column Grid misalignment

### ISSUE THREAD

**Issue by jimmy-e** [airbnb/visx#1176]
The XYChart's column grids are misaligned with x-axis tick marks. In addition, there appears to a gap between the chart and the y-axis.

![image](https://user-images.githubusercontent.com/25621956/115166627-1bf27800-a082-11eb-99c8-59e1dc98830a.png)

**Comment by jimmy-e** [comment]
btw did this pr resolve the gap between the chart and the y axis as well or just the grid / tick alignment?

**Comment by williaster** [comment]
From the PR 
> Note the gaps on the side of the chart described in the issue can be controlled by setting the band scale padding config to 0.
