### ISSUE TITLE
[xy-charts] Tooltip's nearestDatum breaks down when there's multiple points with the same x axis  

### ISSUE THREAD

**Issue by JeremieBou** [airbnb/visx#1191]
We're working on this chart and having a hard time with Tooltips. Since xycharts uses the nearest point on the x-axis as `nearestDatum`, the behavior makes it hard to make tooltips work when there's multiple points on the same x-value.

Ideally, we would either be able to make tooltips for each value in the same x location, or the calculation would take into account the y-axis distance too in order to get a more accurate `nearestDatum`.  

https://user-images.githubusercontent.com/5090485/116623733-8bc2f700-a8fb-11eb-9161-0112c1037175.mov

**Comment by williaster** [comment]
Hey @JeremieBou thanks for the bug report! I'm going to close this as it duplicates #979. It shouldn't be too difficult to fix/add logic for the nearest `y` values, I just haven't had bandwidth. Happy to help review a PR if you or others are interested!

This is the relevant file https://github.com/airbnb/visx/blob/master/packages/visx-xychart/src/utils/findNearestDatumSingleDimension.ts#L7:25

**Comment by JeremieBou** [comment]
Thanks I'll take a look at that thread
