### ISSUE TITLE
Pie chart slice color?

### ISSUE THREAD

**Issue by omasback** [airbnb/visx#1193]
It seems not possible to assign different colors to different pie slices using the `<Pie>` props. Is there any way to do this without resorting to manually coding the children slice elements? Seems like an easy feature to provide that could save a lot of boilerplate.

**Comment by goldenivan** [comment]
Hi @omasback,

You can specify the color of the pie in the path, especially the "fill" value. If you set "blue", all pies will be blue. If you define in your dataset a color property, you can use it like this : 
```
 <path d={pie.path(arc)} fill={data.color} />
```

An example of that : https://codesandbox.io/s/tf4ed?file=/Example.tsx:1783-1837

Regards,

**Comment by williaster** [comment]
Yes this is a limitation discussed in this discussion thread https://github.com/airbnb/visx/discussions/1177 where I also suggested a simple feature implementation.

We can track with this issue, I'm happy to review a PR if anyone is interested!

**Comment by omasback** [comment]
@williaster that perfectly answers my question, thanks!

**Comment by iampueroo** [comment]
Hello @williaster . If no one is tackling this I can take this, but let me first try to communicate what I think the problem and fix actually is:

The core problem seems to be that the `Pie` [component](https://github.com/airbnb/visx/blob/master/packages/visx-shape/src/shapes/Pie.tsx#L85) does not allow _dynamic_ slice colors (the `fill` property) by default, and thus the user is required to render child `<path>` components by hand to pass through dynamic colors.

To fix this, the Pie component can have the `fill` prop be both a `string` (as it is today), but also a string accessor function. The function will be called and passed each arc datum, and returns the string for that datum's color. This way, a pie-chart with different colors can be built out-of-the-box (without custom children).

-----
So, in the end the example code will look like this (I took this from #1177):
```js
 <svg width={width} height={height}>
        <Group top={centerY + margin.top} left={centerX + margin.left}>
          <Pie
            data={letters}
            pieValue={frequency}
            pieSortValues={() => -1}
            outerRadius={radius}
            innerRadius={radius - donutThickness}
            fill={(datum) => getLetterFrequencyColor(datum.data.frequency)} // This would be new
          />
        </Group>
</svg>
```
and Pie's component will look like this:
```js
// Other stuff...
const fillAccessor = generateFillAccessor(fill); // Casts a `string` value to the identity function
// More other stuff
return (
    <Group className="visx-pie-arcs-group" top={top} left={left}>
      {arcs.map((arc, i) => (
        <g key={`pie-arc-${i}`}>
          <path className={cx('visx-pie-arc', className)} d={path(arc) || ''} fill={fillAccessor(arc)} {...restProps} />
          {centroid?.(path.centroid(arc), arc)}
        </g>
      ))}
    </Group>
  );
```
Does that align with your thinking?

**Comment by williaster** [comment]
Hey @iampueroo! Thanks for writing this up, this all looks good to me 💯  and I'm not aware of anyone else who's looking to tackle it. I'll keep an eye out for a PR whenever you have bandwidth! 👀

**Comment by iampueroo** [comment]
@williaster create a PR above^

Out of curiosity is there a preferred way of adding "simple" examples? I noticed #1061 mentions adding "simple" examples, but is that in regards to the [gallery](https://airbnb.io/visx/gallery)? I ask since I actually added a simple pie chart example to the gallery when testing out my changes.
