### ISSUE TITLE
Label trouble on Firefox

### ISSUE THREAD

**Issue by goldenivan** [airbnb/visx#1194]
Hello,

I'm using Label on a pie chart. On chrome and safari, I don't have any problems. But on Firefox, I have one.

On the render of the page, everything seem's fine. But when I resize the page, the labels are all pushed up by 140px.

I tried this on a simple example on [codesandbox](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-annotation?file=/Example.tsx), and I saw that : 

On Chrome : 

![MVfVO4jCLC](https://user-images.githubusercontent.com/12681339/116884733-5da92400-ac27-11eb-994d-5042494e8646.gif)

On Firefox :

![v7YUYR4aEr](https://user-images.githubusercontent.com/12681339/116884745-60a41480-ac27-11eb-919d-f54cf6c8da27.gif)

You can see that, before doing anything, the label on Firefox has a bigger height. When I resize the windows on Chrome, there is no issue. But on Firefox, the label get all the size he has.

Do you have any idea what could it be ?

Regards,

**Comment by williaster** [comment]
Thanks for reporting! This duplicates #1111 for which there is also a PR/fix out for. I'll try to review it again today and hopefully we can get it out today/tomorrow.
