### ISSUE TITLE
Is it possible to iterate through each bar in XYChart?

### ISSUE THREAD

**Issue by jimmy-e** [airbnb/visx#1197]
### Part 1
Please see [this codesandbox](https://codesandbox.io/s/zealous-mendel-fm48s?file=/Example.tsx:2499-2550), specifically line 95. My question is, how can I, using `XYChart`, iterate through each and every row so I can add (for example) custom titles, images, etc to every row?

### Part 2
Please see [this codesandbox](https://codesandbox.io/s/condescending-bhabha-7y097?file=/Example.tsx:3474-3517). This is what I am trying to accomplish with Part 1. However, why isn't my custom header for each row `<h1>hello world</h1>` showing up? Thanks.

**Comment by williaster** [comment]
Hi @jimmy-e , `@visx/xychart` is a high-level abstraction and doesn't currently support you rendering custom bars within a stack. You would have to write your own `Series` and leverage the `XYChart` data context as outlined in the `Advanced Usage` section of the docs, or use the low-level `BarStack` from `@visx/shape` you mention in your second example.

As for the second example, you are rendering an `<h2>` element as a child of and `svg` element (nearly all visualizations in `visx` are `svg`-based, not `html` based), which is not valid. Here's an [example](https://codesandbox.io/s/falling-dew-0n80p) using `svg` `<text />` instead. also you rendered the rect after/on top of the `text`, so the `rect` would also hide the text had it been rendered. So I moved it to render on top of the `rect`.

**Comment by jimmy-e** [comment]
Thanks @williaster for the help!
