### ISSUE TITLE
scaleBand w/ dates doesn't plot over entire range

### ISSUE THREAD

**Issue by nvolungis** [airbnb/visx#1215]
I've created a [minimal example here](https://codesandbox.io/s/optimistic-architecture-bgkhc). I have two data points with dates + int values. Dates are plotted against the x and ints against the y. The issue is that y values are cut in half relative to the range. when I use 3 data points, they're cut by 1/3. I'm sure this is a misunderstanding of how to set things up on my part, but I'm pretty stuck. 

Thanks for your help.

**Comment by williaster** [comment]
Hey @nvolungis thanks for checking out `visx`! I get an empty sandbox when I follow that link, could you update it or share another?

**Comment by nvolungis** [comment]
Hey @williaster. I updated the comment with this link here https://codesandbox.io/s/optimistic-architecture-bgkhc. Thanks for looking!
