### ISSUE TITLE
Cant find a documentation for BarGroup

### ISSUE THREAD

**Issue by kostozy** [airbnb/visx#1217]
Hi there! I've seen the example, https://airbnb.io/visx/bargroup
Need something like that, but I can't create it zoomable with brush like https://airbnb.io/visx/brush 
So I've tried to find some descriiption about that 'BarGroup' component, however can't see anything. Could you help me and add it to docs? https://airbnb.io/visx/docs/shape

**Comment by williaster** [comment]
Hey @kostozy 👋  thanks for checking out `visx`! Thanks for opening this issue, I just created #1212 earlier this week to fix this problem which I noticed. It should land soon and this should be fixed, sorry for the bug!

**Comment by williaster** [comment]
the demo site should be updated momentarily / in the next ~10 minutes
