### ISSUE TITLE
Some troubles with using brush with group bar chart

### ISSUE THREAD

**Issue by kostozy** [airbnb/visx#1226]
![image](https://user-images.githubusercontent.com/4223563/119837192-05ee9780-bf0b-11eb-9fd8-679d74b2bbf7.png)
seems like something not working with scaleBand and brush change, however I admit that I was mistaken somewhere
https://codesandbox.io/s/gracious-knuth-vp3ji?file=/Example.tsx

**Comment by kostozy** [comment]
So when I'm trying to move it to left\right, like here https://airbnb.io/visx/brush, it has bounds x0 and x1 always changing

**Comment by kostozy** [comment]
Seems like I should operate with xValues only?

**Comment by Stuhl** [comment]
I'm having the same problem. How did you fix it?

**Comment by christianpur** [comment]
Running into this issue as well, is there a fix?
