### ISSUE TITLE
Unique Key Error on BarGroup

### ISSUE THREAD

**Issue by letsandeepio** [airbnb/visx#1250]
I have defined the `defaultKeys` as well as the 'key' attribute on the top-level custom tooltip component and tried everything still getting the below error on the console:

Warning: Each child in a list should have a unique "key" prop.  Check the render method of `BarGroup`. See https://reactjs.org/link/warning-keys for more information.

```tsx
<BarGroup
      data={data}
      keys={defaultKeys}
      height={maxValues.Y}
      x0={getWeek}
      x0Scale={scales.xScale}
      x1Scale={scales.weekScale}
      yScale={scales.barScale}
      color={scales.colorScale}
    >
      {barGroups =>
        barGroups.map((barGroup, i) => {
          const groupWidth = barGroup.bars
            .map(bar => bar.width)
            .reduce((a, b) => a + b);
          return (
            <Tooltip
              arrow
              title={
                <>
                  Sample Tooltip
                </>
              }
              placement="right"
              key={`bar-container-${barGroup.index}-${i}`}
            >
              <rect
                x={barGroup.x0 - 2}
                width={groupWidth + 6}
                height={maxValues.Y}
                fill="#cecece"
                style={{
                  opacity: highlight === barGroup.index ? 0.3 : 0
                }}
                onMouseOver={() => setHighlight(barGroup.index)}
              />
            </Tooltip>
          );
        })
      }
    </BarGroup>
```

**Comment by williaster** [comment]
Hey @letsandeepio thanks for checking out `visx`. It's hard to debug this without a full codesandbox or similar to reproduce. It looks like you're **not** using the `@visx/tooltip` `<Tooltip />` is that correct? Since you're putting the `key` on that component it seems like it is probably the issue. 

Have you tried removing the tooltip and instead putting the key on `<rect />` to see if that fixes it? that would help narrow it down to the `<Tooltip />` and not a `visx` issue.

**Comment by letsandeepio** [comment]
Hi @williaster thanks for replying. Yeah been using and enjoying VisX for some time, and it is so powerful and intuitive at the same time basically in love with it since the first day.

Back to the issue at hand, so yes I am not using the Visx Tooltip component and you are right the issue goes away when using the key on the <rect>, but then I tried adding a top-level div with a key just above the Tooltip component as well, the issue still persists. 

Will creating a sandbox version of this help in figuring out why this might be happening?

**Comment by letsandeepio** [comment]
@williaster and my bad I did not check that Discussions were enabled, do you want me to close this issue and move it there?

**Comment by kristw** [comment]
@letsandeepio Moving to discussion would be great. Thanks!

**Comment by letsandeepio** [comment]
@williaster was right - this was an issue with the third-party component. I have resolved it. Thanks for the suggestions!
