### ISSUE TITLE
Add `colorAccessor` prop to XYChart LineSeries

### ISSUE THREAD

**Issue by johnathanludwig** [airbnb/visx#1260]
A few of the XYChart series components like BarSeries support providing a `colorAccessor`. This is convenient when you want to specify a specific color for each series.

It would be nice if this support could be added to LineSeries as well. 

Currently you either need to modify the theme and track specific indexes to modify the correct colors, or specify a stroke, but the downside of the stroke is it doesn't update glyph you get when hovering.

**Comment by chrisella** [comment]
I need this and cannot fathom why it was added to other series types and not LineSeries ?
I have a chart where the series colours are inconsistent and change as the data changes / I hide series etc.

![VisxInconsistentColours](https://user-images.githubusercontent.com/1069324/125084041-ff823c80-e0c0-11eb-9eb8-698ae9089460.gif)

I have tried various hacky ways to try and force this or workaround but to no avail.

**Comment by williaster** [comment]
sorry for the delay, agree this could be a good addition. I don't have bandwidth right now but happy to review a PR if anyone is interested. #1005 should be good to model off of.
