### ISSUE TITLE
Add the ability to customize a stroke per side

### ISSUE THREAD

**Issue by JoeVanGundy** [airbnb/visx#1274]
Hi there, just getting started so I apologize if this is a duplicate (couldn't find anything).

From what I know, there is only `strokeWidth` and `stroke`.
I want to remove the stroke on the left and right side of a plot.
Is this possible/can it be added?

![image](https://user-images.githubusercontent.com/8807246/125528276-89bea01f-a850-4eab-b0a1-3fafd1b02783.png)

**Comment by williaster** [comment]
Hi @JoeVanGundy 👋  thanks for checking out `visx`. Currently it looks like you're using an `Area` shape, which in SVG is drawn as a single shape with fill and stroke around the entire shape as you see.

So what you're seeing is an SVG limitation, nothing specific to `visx`. To achieve the effect you want I would recommend 
- removing the stroke from `Area'
- overlaying a `LinePath` from `@visx/shape` on top of the `Area`, which will only draw a shape along the top of your chart

Check out this [sandbox](https://codesandbox.io/s/ecstatic-joliot-sbu39?file=/Example.tsx) for a demo, let me know if you have any other questions.

![image](https://user-images.githubusercontent.com/4496521/125530491-8076406b-4f9f-4052-b559-37932b9f846c.png)

**Comment by JoeVanGundy** [comment]
@williaster Thanks so much for your quick response! This is perfect!
Coming from Vega/Altair and starting to get the feel of Visx more now.

Still had one more pain-point that I couldn't figure out that is stopping us from switching over.

I need to generate an SVG on the backend and send the result via email. Are there any recommendations for handling this? Or should I just be thinking about Visx the same way I would handle create D3 plots?

I also just found the slack channel, so I'll ask there! Feel free to close the issue!

Thanks!!

**Comment by williaster** [comment]
thanks @JoeVanGundy 🙏 

> I need to generate an SVG on the backend and send the result via email. Are there any recommendations for handling this? Or should I just be thinking about Visx the same way I would handle create D3 plots?

I would generally think of `visx` as similar to `d3`, low-level SVG generation. I would note that currently `visx` doesn't support `canvas` rendering (it has been discussed but would need a decent amount of work). In any case, we have had success generating vis images with visx in nodejs with something like this:

```tsx
import ReactDOMServer from 'react-dom/server';

// create a react component for your chart
const MyChart = () => <svg><LinePath {...} /><Axis {...} /></svg>;

// render it to a string
import ReactDOMServer from 'react-dom/server';
const svgString = ReactDOMServer.renderToString(<MyChart {...props} />);

// convert to a png
import svg2img from 'svg2img';
import Canvas from 'canvas';

// register font or styles with node canvas
Canvas.registerFont('./frontend/themes/fonts/Airbnb_Cereal-Light.woff', {
  family: labelStyles.fontFamily,
});

svg2img(svgString, function(error, buffer) {
  // returns a Buffer, which you can write to a file or return as an http response
  // see https://www.npmjs.com/package/svg2img docs
    fs.writeFileSync('foo1.png', buffer);
});
```

Gonna close for now but feel free to re-open/open other issues, or reach out on slack 👍
