### ISSUE TITLE
Is onBrushEnd broken for the Brush component?

### ISSUE THREAD

**Issue by JoeVanGundy** [airbnb/visx#1283]
Is onBrushEnd broken for the Brush component?

The docs say: `Callback invoked on mouse up when a Brush size is being updated`.

Not sure if I’m misunderstanding what this is suppose to do, but  I would expect this callback to only fire when the user lets go of a mouse drag. Instead, I’m seeing it fire every time the value of the brush changes.

I'm keeping track of the current start and end dates using `useState`.
Since `onBrushEnd` is being calling so many times, I'm setting the state like 50 times during one short drag and performance is tanking hard.

Thanks!

**Comment by williaster** [comment]
Yep this is definitely broken. This may have been introduced in a recent update [here](https://github.com/airbnb/visx/pull/1164/files#diff-4c772d3f29c55ad72ca74a21c447728c9cb63e12caa597b1b32d5d1cb3adffe3R259) and is specific to when `useWindowMoveEvents={true}`. 

Shouldn't be too hard to fix, I'll try to get something out today.

**Comment by williaster** [comment]
closed by #1286

**Comment by JoeVanGundy** [comment]
> closed by #1286

@williaster Forgot to say thanks for fixing this so fast!!
