### ISSUE TITLE
[XYChart] Tooltip provoking overflow

### ISSUE THREAD

**Issue by jnfrati** [airbnb/visx#1297]
Hello everyone! I'm having some overflow when I hover on the end of the xAxis. From what I think is that the tooltip is having some really weird behavior but didn't knew how to properly debug it.

[Here is an example](https://codesandbox.io/s/ecstatic-architecture-zcis8?file=/src/Chart.tsx)

And I'll leave a recording just in case it's useful

https://user-images.githubusercontent.com/23369263/127589187-db647b68-bcda-4106-8b13-1be7ba562443.mp4

I'm really new on using visx so it's probably something missing on the chart configuration, but as I didn't manage to find anything to fix this I thought it could be probably an issue.

**Comment by williaster** [comment]
hey @jnfrati 👋 , thanks for checking out `visx`. `Tooltip`s in `@visx/xychart` are rendered **inside a [React portal](https://reactjs.org/docs/portals.html)**, outside the `svg` and appended as new nodes to `<body />`. This is done to prevent tooltip clipping by other elements on the page.

(note there is one for each of the tooltip, crosshair(s), and series glyph(s))
![image](https://user-images.githubusercontent.com/4496521/127701768-8e71f0c0-d9c2-4f5a-ac13-519d5f07bf8d.png)

So I think in your case you need to add `overflow: hidden` to the `body`. [Here's a working sandbox](https://codesandbox.io/s/polished-surf-rn5qm?file=/src/Chart.tsx), note it is also modified to support dynamic width so it will update with screen size.

![image](https://user-images.githubusercontent.com/4496521/127701656-314e5adb-012a-473a-9d2f-7585caa791d6.png)

Hope that helps, feel free to reopen if not!

**Comment by jnfrati** [comment]
Thank you for the help @williaster! That solved the problem 🙌
