### ISSUE TITLE
Tooltip: pass flipped by bounds flag to `renderTooltip` component

### ISSUE THREAD

**Issue by joernroeder** [airbnb/visx#1329]
I'd love to updated the styling of the tooltip content based on a flag which indicates whether the tooltip is show on the left or right of the vertical crosshair. Something like `isFlippedVertically` and `isFlippedHorizontally` would make sense to me and it looks like its literally just using `!placeTooltipLeft` and `!placeTooltipUp` as their values https://github.com/airbnb/visx/blob/master/packages/visx-tooltip/src/tooltips/TooltipWithBounds.tsx#L51

**Comment by mkim871** [comment]
+1
