### ISSUE TITLE
Voronoi: High memory usage (OOM in browser in some cases)

### ISSUE THREAD

**Issue by sebastianpantin** [airbnb/visx#1330]
Hi! I noticed a problem with the Voronoi library where it sometimes can end up using a lot of memory (Well, chrome does but you get the point..). It seems to get into some kind of infinite loop when it calculates the voronoi, I think. 

I created a [codesandbox](https://codesandbox.io/s/goofy-cherry-pc739?file=/Example.tsx&resolutionWidth=692&resolutionHeight=796) with data that makes it get into this state. 

To reproduce:
1. Enter responsive mode in codesandbox
2.  Start resizing the window until you get an error 
3. Reload the page and watch your chrome resource use a lot of memory until it eventually crashes.

There seems to be an issue about it on the ["d3-voronoi"-page](https://github.com/d3/d3-voronoi/issues/33) but they recommended that you reimplement it using "d3-delaunay". What do you think would be the best approach for visx? Reimplement it using "d3-delaunay" or wait until "d3-voronoi" is fixed? For my project I implemented it by using "d3-delaunay" instead.

**Comment by williaster** [comment]
Hi @sebastianpantin 👋  thanks for reporting this, I haven't hit the OOM issue before but there was a [discussion](https://github.com/airbnb/visx/discussions/1272) about adding a new `@visx/delaunay` package and deprecating `@visx/voronoi` to be in sync with the `d3` developments.

We can use this issue to track that. I don't currently have the bandwidth to do this but would happily review a PR if someone is interested 🙌

**Comment by SheaJanke** [comment]
I'm willing to give this a shot!

What is the best way to handle the sandbox examples for a new package? I can't import from @visx-delaunay until the new package is released to npm. Do I just add it in a separate PR afterwards once the package gets released?
