### ISSUE TITLE
Zoom event with key shift

### ISSUE THREAD

**Issue by 6vvvvvv** [airbnb/visx#1334]
Is there a way that zoom in or zoom out event only happens when we have mousewheel + key shift?

I have set passive = true and the scroll event works fine but when I have onWheel=zoom.handleWheel, the zoom and scroll event happen at the same time.

![image](https://user-images.githubusercontent.com/47306004/131860769-17f2d29c-2aba-483e-b2de-7f3c0dfeb5ff.png)
![image](https://user-images.githubusercontent.com/47306004/131860862-3cb1e2fd-3b1f-4566-b101-63e279887d9f.png)
![2021-09-02-16-29-10](https://user-images.githubusercontent.com/47306004/131864514-dac3ce66-f744-42b9-aebe-ae2113315b24.gif)

Thanks for helping to solve this problem.

**Comment by williaster** [comment]
hey @6vvvvvv which version of `@visx/zoom` are you using? this may have been fixed in the `2.0.0` release (the scroll + zoom simultaneously) as it was reimplemented using [`useGesture`](https://use-gesture.netlify.app/) in https://github.com/airbnb/visx/pull/1305.

**Comment by jithureddy** [comment]
Hey @6vvvvvv I am also starting to work on some complex hierarchical view. So did you consider foriegnObject for each tree node ?

**Comment by 6vvvvvv** [comment]
> 

Yes. And it works as expected for a long time.
