### ISSUE TITLE
Issue with bars going below 0

### ISSUE THREAD

**Issue by JoeVanGundy** [airbnb/visx#1338]
Hi there

I'm implementing a waterfall plot for our app.
The plot works as expected with positive values, but when I have a bar goes a yAxis value of 0, the yScale gets messed up.

When I'm calculating the height of a bar, it always return a bar with the height of the full plot which is incorrect.
When I throw in a bar that goes below 0, it messes up the the positive bars as well, which leads me to believe it has to do with my yScale domain, but it seems completely correct to me.

Here is a simplified code sandbox of the issue:
https://codesandbox.io/s/stoic-glitter-uiwf8?file=/Example.tsx

**Comment by williaster** [comment]
Hi @JoeVanGundy I think this is an issue with your data/calculations. In your example, the y-domain extent is `[10, 10]` based on the 3 data points you provided and the way you compute the y-value which is always positive (when you use the delta to compute the y-domain, you are using **bar height** to compute the domain which doesn't work). if you add a value besides 10, and compute the extent using the bar top/values separately, the y-scale changes as expected.

On top of that I think your bar `y` + `height` calculations are off. you set the top position of the bar based on `yScale(getBarTopValue(d))` which I think is correct, but height is always `yMax - yScale(getBarValueDifference(d))` which breaks with negative values, and I think it needs to be `yScale(getBarTopValue(d)) - yScale(getBarBottomValue(d))`.

Here's [another sandbox](https://codesandbox.io/s/confident-mahavira-p1ucn).

![image](https://user-images.githubusercontent.com/4496521/132394496-7c5b51df-ba7a-4bb6-8c40-e2246acadb45.png)
