### ISSUE TITLE
Vertical positioning of tick labels on vertical axes

### ISSUE THREAD

**Issue by dumbmatter** [airbnb/visx#1374]
I'm porting a couple charts from D3 to visx and overall it's going great. But one thing I noticed was that the positioning of tick labels on vertical axes is a bit different.

Here is the D3 version:

![image](https://user-images.githubusercontent.com/828632/142462146-02ad1936-3921-44d0-8051-f95a80fca0c6.png)

And here is the visx version:

![image](https://user-images.githubusercontent.com/828632/142462173-ff72ba7e-b3da-4df4-a5b3-20b1484598cb.png)

As you can see, the D3 tick labels are centered relative to the tick, but the visx ones are shifted up slightly.

I was dreading having to extract this from my app to make a self-contained example for this bug report... but then I noticed [this example from the visx website](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-threshold) has the same exact issue:

![image](https://user-images.githubusercontent.com/828632/142462412-476eccc0-080a-4c62-91fe-72072a655138.png)

Just like in the screenshots from my app, the tick labels are not quite centered relative to the ticks. IMHO it'd look better if they were centered, and I'm not sure why someone would want them slightly off center, so I'm guessing this is a bug. Or is it intentional that they are positioned like this?

**Comment by hshoff** [comment]
Hi @dumbmatter, this happens due to the defaults for [`tickLabelProps`](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/axis/AxisLeft.tsx#L20) on `<AxisLeft />`. Can adjust the vertical positioning of the axis tick value using `dy`.

```jsx
<AxisLeft 
  scale={temperatureScale} 
  tickLabelProps={() => ({
    fontSize: 14
    fontFamily: "Arial",
    textAnchor: 'end',
    dx: '-0.25em',
    dy: '0.33em' // change me 
  })
} />
```
