### ISSUE TITLE
[XYChart] [LineSeries] Problems with vertical axis and showing the value of each point on the graph in the series of lines

### ISSUE THREAD

**Issue by danielsouza21** [airbnb/visx#1378]
Hello,

I have some questions and issues when creating a new XYChart component for me. In this sense, I would like some help in this regard, as my chart is just series.

1. Is it possible to somehow configure labels for each point of the graph? My intention would be to add something like this:

   <img src="https://user-images.githubusercontent.com/70732405/142915262-ffe54fed-d4e8-4cc9-8196-36ed990443a1.png" width="200">

    I already thought about using annotations, but the first tests didn't have good results and the implementation was being complex. Is there a simple native library solution?

2.  How can I change the Y scale so that it is possible to fix the minimum and maximum value automatically with the data of the series shown? Currently, my graph always starts with a value of 0 and the maximum of the vertical axis is a little smaller than what I wanted. In this sense, I would like to configure these axis to automatically perform a correct zoom in the series.

     The image below is a print of my current component. As highlighted, my vertical scale is a little smaller than the maximum of the graph and it always starts at 0. Is there any way to change this?

    <img src="https://user-images.githubusercontent.com/70732405/142916690-23f53d1e-3ed0-444f-8d1c-e8fb915ca6ba.png" width=800>

The screenshot below is of the prototype which represents the result I want to achieve:
<img src="https://user-images.githubusercontent.com/70732405/142920507-48c94f82-6d03-42f9-8887-d101e4b701ce.png" width=800>

A fraction of the code has been added to CodeSandbox to exemplify the current implementation. 

<p align="center">
<a href="https://codesandbox.io/s/xygraphtest-eluzi?fontsize=14&hidenavigation=1&theme=dark&view=editor">
  <img alt="Edit XYGraphTest" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>
</p>

**Comment by hshoff** [comment]
Hi @danielsouza21, for `2`, you can tune your `verticalScaleConfig` like so:

```js
  const verticalScaleConfig = { type: "linear", zero: false, nice: true };
```
![image](https://user-images.githubusercontent.com/339208/147982644-aa485a86-ea70-4d61-95be-38d2c5fb261b.png)

For `1`, you can use `<AnimatedGlyphSeries />`:

```jsx
 <AnimatedGlyphSeries
  key={`${item.dateKey}-glyph`}
  dataKey={item.dateKey}
  data={data}
  xAccessor={accessors.x.date}
  yAccessor={item.accessor}
  stroke={item.color}
  strokeDasharray={item.strokeDasharray}
  curve={curveCardinal}
  renderGlyph={({ datum, x, y, key }) => {
    return (
      <text
        key={`${x}-${y}-${key}`}
        textAnchor="middle"
        dy={"-0.33em"}
        fill={item.color}
        fontSize={10}
        x={x}
        y={y}
      >
        {formatter(datum[item.dateKey])}
      </text>
    );
  }}
/>
```

![image](https://user-images.githubusercontent.com/339208/147984528-ae0ddeb1-3717-460a-b1c5-049d84d32d08.png)

Hope this helps! https://codesandbox.io/s/xygraphtest-forked-jxfvx?file=/src/components/xychart/ChartComparative.jsx
