### ISSUE TITLE
Performance issue with 10k+ data points and zoom functionality

### ISSUE THREAD

**Issue by MacaScull** [airbnb/visx#1381]
I want to use Visx scatter plots to plot 10k+ points, while also having the ability to zoom in on these points and eventually have tooltips on top of this too. 

I've got a working example of the 10k+ points and a zoom feature incorporated, though this is extremely laggy so can visx scatter plot and zoom support this amount of data and how can I improve its performance? I was wondering how I could increase performance of this so theres no lag, as eventually I want to plot 30k+ points.

To get my example I mixed the code from both the zoom (https://airbnb.io/visx/zoom-i) and scatter plot (https://airbnb.io/visx/dots) code and increasing the data generation from 600 to 15000 instead.

**Comment by hshoff** [comment]
Hi @MacaScull, for rendering 10,000+ points you'll want to avoid svg and instead use canvas or webgl. If you want to stick with svg you'll want to do some clustering of the points and try to keep it in the 500-1000 range. Hope this gets you pointed in the right direction and good luck with your project!
