### ISSUE TITLE
Vertical brush not working as expected

### ISSUE THREAD

**Issue by Avi-Patel** [airbnb/visx#1385]
when i passed `useWindowMoveEvents: true`, horizontal brush works fine but vertical brush starts causing problems.

1. when i drag bottom end of brush, whole brush moves along brush line.
2. when i drag top end of brush, it does not move.
3. brush selection move works as expected

`resizeTriggerAreas` are `['top', 'bottom']`

**Comment by williaster** [comment]
fixed by https://github.com/airbnb/visx/pull/1522
