### ISSUE TITLE
xychart - Control number of rows and columns grid lines

### ISSUE THREAD

**Issue by TiagoPortfolio** [airbnb/visx#1388]
Hi all! 👋 

I would like to control the number of row and column grid lines separately in a xychart but this seems to not be possible at the moment.
At first, I tried using the `numTicks` prop on the **Grid** component but this prop will affect both rows and columns ticks when I only want to change the number of row grid lines.
Secondly, I used the `numTicks` prop again but this time on the **Axis** component with orientation "left" responsible for the rows. This didn't have any effect.
And at last, I used the `tickValues` prop on the same **Axis** component with the value `[1, 2, 3, 4, 5]` because I want 5 grid row lines but instead I got a grid line for 1, 1.5, 2, 2.5 and so on...

Are there any plans in the roadmap to make controlling the number of rows and columns grid lines possible?
Cheers! 🍻

**Comment by hshoff** [comment]
Hi @TiagoPortfolio, yes this is possible but you need to provide your own `<CustomGrid />`:

```jsx
function CustomGrid() {
  const { xScale, yScale, innerHeight, innerWidth, margin } = React.useContext(
    DataContext
  );
  if (!xScale || !yScale) {
    return null;
  }
  return (
    <>
      <GridRows
        left={margin.left}
        width={innerWidth}
        scale={yScale}
        numTicks={5}
      />
      <GridColumns
        top={margin.top}
        height={innerHeight}
        scale={xScale}
        numTicks={3}
      />
    </>
  );
}
```

![image](https://user-images.githubusercontent.com/339208/148132117-f3dc3b14-d2d6-422c-97ed-080814dac1ab.png)

https://codesandbox.io/s/compassionate-clarke-3jyoi?file=/Example.tsx

**Comment by TiagoPortfolio** [comment]
Thank you @hshoff !
It worked like a charm 😉
