### ISSUE TITLE
Axis labels incorrectly positioned in case of long tick labels

### ISSUE THREAD

**Issue by lehnerchristian** [airbnb/visx#1395]
When using a dataset with high numbers the axis tick labels can get pretty long. If an axis label is added to this axis they will most likely intersect each other (please see left axis label in the following image).
![Screenshot from 2021-12-21 15-08-47](https://user-images.githubusercontent.com/1711080/146943518-198219b7-3332-4f68-b725-79884718e17d.png)

Here's a Codesandbox to reproduce this issue: https://codesandbox.io/s/visx-label-bug-u18kl?file=/src/Linechart.js
The example in the Codesandbox should be pretty straight forward and still I can reproduce the issue easily. Is this something that's going to be fixed in VisX? Or did I misconfigure my chart?

Thanks!

**Comment by gazcn007** [comment]
There are two ways you can fix this problem, you can format your axis tick labels to be shorter like, 500k, 1,000k.
Or you can add left margin and increase labelOffset, which you will get this
![image](https://user-images.githubusercontent.com/12766318/147040513-5feab265-85e7-4112-9ede-9d813cddfed7.png)

**Comment by lehnerchristian** [comment]
Hey @gazcn007 , thanks for your quick reply.

The problem with the first suggestion is that I don't have direct control how the values are displayed. They might be formatted with an abbreviation as you suggested, however they could also be formatted with abbreviation and a unit (which would also be fine) or with a unit and **without** abbreviation (which makes the label even longer)

The second suggestion is exactly what I've done now: in a custom React hook I'm measuring the width of the ticks and move the label by the maximum width (i.e. width of the longest label) and this approach worked fine until I tried to animate the chart when it appears. When it's animated from a width set to 0 to width set to 100% the approach with the offset does not work reliably anymore.

I might be able to change the animation (e.g. only fade, so no change in width is involved), however I think improving this in the library might be a better approach, because otherwise every project has to implement a hook like I described above.

**Comment by hshoff** [comment]
Hi @lehnerchristian, formatting the axis value can be done independently of the data format.  [`d3-format`](https://github.com/d3/d3-format) works well for this but can be any function that takes a tick value and returns a string. 

```jsx
import { format } from 'd3-format';

const formatter = format('.2s');
// ...
<AxisLeft scale={yScale} label="Left label" tickFormat={formatter} />
```

![image](https://user-images.githubusercontent.com/339208/147977144-fc3d453c-3244-4044-a922-cb7d1e6f037f.png)

Hope this helps!
