### ISSUE TITLE
zoom-i demo mini map moves in the opposite direction

### ISSUE THREAD

**Issue by mohsen1** [airbnb/visx#1429]
https://airbnb.io/visx/zoom-i

Chrome 97

https://user-images.githubusercontent.com/543633/151474309-869651af-e3f0-4a83-8918-0feb9c2616a7.mov

**Comment by hshoff** [comment]
Hi @mohsen1! This is not so much a bug, just how the demo it's implemented. There's no drag on the mini map (the zoom+drag interaction is on the wrapping container), so you're still dragging the phyllotaxis "underneath" the minimap. When you drag the phyllotaxis left, the viewport in the minimap is moving right as the minimap phyllotaxis position stays fixed.
