### ISSUE TITLE
AnimatedAxis with time scale: Encountered two children with the same key

### ISSUE THREAD

**Issue by carlsverre** [airbnb/visx#1435]
Similar issues: #1038 and #969

The bug can be reproduced when two time values are very close (within seconds) and animated. This has been reproduced in this codesandbox (see console and click update ticks):
https://codesandbox.io/s/vigilant-booth-5pw3vo?file=/Example.tsx

I believe the bug is caused by this line:
https://github.com/airbnb/visx/blob/master/packages/visx-react-spring/src/axis/AnimatedTicks.tsx#L30

The issue seems to be converting Date objects to strings which effectively truncates them to seconds (the string format is something like `Fri Dec 17 2021 03:24:01 GMT-0800 (Pacific Standard Time)`).

As for a solution, I'm not sure what's best. One option is to take in a key formatter for ticks and leave it up to the programmer, however that seems user unfriendly. Another option is to use a time aware key formatter than converts the date object into a number (thus milliseconds since epoch) and then into a string.

**Comment by mithi** [comment]
FYI, I'm having the same issue but also with `GridRows` and `GridColumns`, will post repro/code sandbox soon
