### ISSUE TITLE
`Brush` does not resize when `width` and `height` props update

### ISSUE THREAD

**Issue by wilson-webdev** [airbnb/visx#1436]
This issue was mentioned [here](https://github.com/airbnb/visx/issues/1282#issuecomment-882815020), but I can't see an explicit issue, so here goes...

**Steps to replicate**:

1. Go to the [Brush example](https://codesandbox.io/s/heuristic-bardeen-luzfu4?file=/Example.tsx)
2. Update the Brush so that it is not the default size 
![Screenshot 2022-02-17 at 12 33 16](https://user-images.githubusercontent.com/24278706/154483725-8e131846-1c77-4612-a949-ebf5793932e5.png)
3. Resize chart and see the Brush has not resized ![Screenshot 2022-02-17 at 12 33 28](https://user-images.githubusercontent.com/24278706/154483777-c8896882-f616-4f32-84fc-a0fa8edc7628.png)

**Comment by williaster** [comment]
thanks for reporting this @wilson-webdev 🙏  I don't have bandwidth to address it at the moment but happy to review a PR 👀

**Comment by williaster** [comment]
fixed by https://github.com/airbnb/visx/pull/1536
