### ISSUE TITLE
<BarSeries> bars have 0 width when using time scale

### ISSUE THREAD

**Issue by elliooo** [airbnb/visx#1457]
**Question:** 
Is there a way to increase the width of `<BarSeries>` bars when using an `<XYChart>` with x-scale of type `time`? If not, what is the recommended solution for using bar charts with time data (specifically dates and date_time data)?

**Context:**
I have a `<BarSeries>` that is being plotted on an `<XYChart>` with x-scale of type `time`. While the bars are rendered, they have 0 width and thus appear invisible:
![Screen Shot 2022-03-24 at 11 05 48 AM](https://user-images.githubusercontent.com/16812885/159982224-b63ff77e-95bb-4fdb-84d4-788739d2921a.png)

I know that using type `band` would be a solution here, but the problem is that the data I receive is not guaranteed to have filled-in dates (i.e. the data could jump from 09-07-2022 to 10-01-2022 without data points in between). In which case, I could ideally use a `<BarSeries>` with a time scale to avoid any mishaps when missing filled-in dates.

**Things I've Tried:**
- I've tried to using the `barPadding` prop to increase the width, but to no avail.
- Using a line series on the same dataset works fine fwiw:
![Screen Shot 2022-03-24 at 11 12 36 AM](https://user-images.githubusercontent.com/16812885/159982987-93dd3394-f308-4de3-8c46-c82117327a97.png)
-  I tried looking into both the "Issues" and "Discussions" sections for previous issues regarding bar chart with time scales, but couldn't find anything.

Cheers!

**Comment by sargentieri** [comment]
@elliooo find a work around to this?
