### ISSUE TITLE
Brush prevents other hover events from firing

### ISSUE THREAD

**Issue by jannikkeye** [airbnb/visx#1464]
Hi everyone,

when I use brush in my charts for selecting data points, any other hover events, for example triggering a tooltip, are not firing.

Is this expected behavior or am I using it wrong?

**Comment by jmssnr** [comment]
Experiencing the same issue

**Comment by jmssnr** [comment]
I got this to work. Please check out this [codesandbox example](https://codesandbox.io/p/sandbox/visx-brush-hover-mhkxwn?file=%2Fsrc%2Findex.tsx). The key is the placement of the Brush component, which should come first.

So I guess this issue could be closed? @williaster

**Comment by hshoff** [comment]
Hi @jannikkeye, @jmssnr is correct. The render order of <Brush> is important here to allow events to be captured. Make sure the items with tooltips are "on top of" the brush as illustrated here in https://codesandbox.io/p/sandbox/visx-brush-hover-mhkxwn?file=%2Fsrc%2FExample.tsx%3A87%2C1-120%2C1
