### ISSUE TITLE
Brush: "An update was scheduled from inside an update function" warning when using "resetOnEnd"

### ISSUE THREAD

**Issue by rarenal** [airbnb/visx#1465]
### Problem
When using [resetOnEnd](https://airbnb.io/visx/docs/brush#Brush_resetOnEnd) in a Brush and after there's a brush end event, the following React warning is thrown
`Warning: An update (setState, replaceState, or forceUpdate) was scheduled from inside an update function. Update functions should be pure, with zero side-effects. Consider using componentDidUpdate or a callback.`

This error is also reproducible if instead of using "resetOnEnd" the brush reference is used inside an "onBrushEnd" to call directly the "reset()" function
```ts
const handleBrushEnd = () => {
    if (brushRef?.current) {
      brushRef.current.reset();
    }
  };
```
### Steps to reproduce
I created [this demo](https://codesandbox.io/s/interesting-feather-dhpfsg?file=/Example.tsx:3468-3603) which basically consists of the Brush example with the "resetOnEnd" attribute.

1. Open CodeSandbox console.
2. Create a new brush area by dragging
3. On the brush end, check how the warning appears in the console.

### Attachments
https://user-images.githubusercontent.com/11938799/161697698-adb7593a-16f5-4cf8-a89c-8918a50995fe.mov

**Comment by gidesan** [comment]
I'm experiencing the same issue

**Comment by lancefaler** [comment]
I also am seeing this same error.  Any insight as to the cause/solution?

**Comment by kethiri-fm** [comment]
I am also facing the same issue. Any updates on this?

**Comment by rafaelsmgomes** [comment]
Also facing the same issue.

Wondering if anyone has got a solution.

**Comment by GerardGarcia** [comment]
Same here, anyone manage to fix it?

**Comment by VGamezz19** [comment]
Same issue here, any update about it?

**Comment by williaster** [comment]
Thanks to @dsdevgit for the fix here! https://github.com/airbnb/visx/pull/1778
