### ISSUE TITLE
React upgrade to 17/18

### ISSUE THREAD

**Issue by erosval** [airbnb/visx#1470]
No planning for react 17 ot 18 support?

Has the project been abandoned?

**Comment by gazcn007** [comment]
The project supports React v17. Is React v18 support blocking your project development? I can work on that if needed

**Comment by erosval** [comment]
Sorry, I notice now that I had lost the update of the package name from vx to visx.

Switching to React 18 doesn't stop me. Thank you very much

**Comment by andreido** [comment]
The project that I'm working on requires support for React v18.

@gazcn007 Would you mind looking into this at your earliest convenience? Would be greatly appreciated!

**Comment by bonesoul** [comment]
also looking for react 18 support.
