### ISSUE TITLE
brush causes area to overflow the axis limit

### ISSUE THREAD

**Issue by alexguja** [airbnb/visx#1523]
Hi there, I'm experiencing an issue with the brush when I try to pass my own data to the Brush chart example.
On the initial state, everything is working as expected, however, when the brush bounds are changed, the area overflows the axis on the right-hand side

<img width="1124" alt="Screenshot 2022-06-02 at 19 27 06" src="https://user-images.githubusercontent.com/60717961/171689019-b4743502-8b7c-422b-bb00-4737d9a0302f.png">

Any ideas on what is causing this? I will look into creating a sandbox later, but some general tips would be great!

**Comment by yeegor-restrata** [comment]
Hi there! Were you able to solve this? I am currently running into exact same issue.

**Comment by alexguja** [comment]
I was able to fix the left side by wrapping the` AreaChart` in an `svg` element with the following props `<svg width={width} height={height}> ... </svg>`, but the right side still persists.. The width and height props come from `ParentSize` as shown in this [sandbox](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-brush?file=/index.tsx)

**Comment by williaster** [comment]
closing without more info/assuming `clamp: true` worked
