### ISSUE TITLE
BarRounded and negative value

### ISSUE THREAD

**Issue by maximekl** [airbnb/visx#1525]
Hi @williaster 👋

I have an issue with `BarRounded` when height values are negatives (here a [codesandbox](https://codesandbox.io/s/historybarchart-p1u675))

<img width="400" alt="Capture d’écran 2022-06-08 à 11 41 21" src="https://user-images.githubusercontent.com/11152214/172585822-8b41f36c-8e1d-4874-807f-15c96ef61e4f.png">

I'm pretty sure, having negative `height` are the problem, but i think `BarRounded` need to handle the problem.

<img width="400" alt="Capture d’écran 2022-06-08 à 11 39 41" src="https://user-images.githubusercontent.com/11152214/172585843-21930fcb-172e-4498-a9ba-a3c685518653.png">

Maybe is more a discution than an issue, i will let you judge this 👌

**Comment by williaster** [comment]
Hey @maximekl 👋  thanks for checking out `visx`. Yeah I think you can fix this by updating the y/height as you did, or I did the following. Gonna close this for now but if there is indeed a problem in the future we can open it back up/create a new issue

```tsx
<BarRounded
  radius={6}
  key={`bar-${year(d)}`}
  x={yearScale(year(d))}
  y={perf(d) < 0 ? perfScale(0) : perfScale(perf(d))}
  width={yearScale.bandwidth()}
  height={Math.abs(perfScale(0) - (perfScale(perf(d))) ?? 0)}
  all={true}
  fill={"#CBCEF2"}
/>
```

<img width="651" alt="image" src="https://user-images.githubusercontent.com/4496521/172724050-773a2203-cfee-4a65-8e3c-2e43d5901bc7.png">
