### ISSUE TITLE
How to customize gestures on Zoom?

### ISSUE THREAD

**Issue by Nieju** [airbnb/visx#1526]
https://github.com/airbnb/visx/blob/35bcb705f37484e502e2fc9d17ec1aaa390dea8f/packages/visx-zoom/src/Zoom.tsx#L319-L342

I would like to use `Zoom` while having a draggable object within an SVG. With the current Zoom implementation when passing `ref=zoom.containerRef` to the SVG a bunch of events get bound to it. However, when I now try to drag an element within the SVG, the whole canvas starts dragging alongside the clicked object being dragged.

How can I make use of some of the default gesture while implementing custom ones for some others?

Thank you :)

**Comment by czescwojtek** [comment]
Any news on this?
