### ISSUE TITLE
svg <line> elements use stroke not fill

### ISSUE THREAD

**Issue by bruce-c-liu** [airbnb/visx#1537]
`fill` has no effect on svg <line> elements. It should use `stroke` instead.

Thus, `<Line/>` from `@vx/shape` should also use stroke.

**Comment by hshoff** [comment]
Hi @bruce-c-liu, thanks for checking out visx.

Correct, `fill` has no effect on svg `<line>` elements and the same is true with `<Line />` from `@visx/shape`, visx just defaults it to `transparent`.

The `fill` attribute is inherited by svg `<line>` so it's a valid attribute: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line#presentation_attributes 

`<Line />` uses `stroke` through the rest props api so `<Line stroke="pink" strokeWidth={3}  ...  />` works as expected. visx defaults `fill='transparent'` to hint that fill has no effect even though it's valid and also to match with the default fill for the more commonly used `<LinePath />`. The `<Line />` fill prop can be removed from the rendered `<line>` attributes by passing `<Line fill={undefined} />`.

I can see how the argument for removing the default fill prop from `<Line>` would make sense, but this would result in a breaking change and wouldn't be fun for the folks that wrote tests around the behavior of their `<Line>`s checking for `fill='transparent'`. So visx will continue with the current implementation as we try to avoid breaking changes as much as possible.

**Comment by bruce-c-liu** [comment]
Makes sense. Appreciate the explanation! :)
