### ISSUE TITLE
XYChart does not derive width as seen in examples

### ISSUE THREAD

**Issue by DingoEatingFuzz** [airbnb/visx#1540]
Hello!

I have a basic XYChart with a height defined, but without also specifying a width, nothing renders.

After perusing the code, I have seen that if either dimension is `0` then rendering is skipped, which makes sense though resulted in a totally confusing developer experience.

I also saw that there is a `setDimensions` function that is provided by the `DataContext` (which I don't fully understand) but it must not be working for some reason?

I have also grabbed example code that works in Code Sandbox but does not work in my app. I wish I had more details to share, but it's quite mysterious and there are no errors or warnings or anything.

### Chart component

```jsx
  return (
    <div className={timeseries}>
      <XYChart height={400} width={1000} xScale={{type: 'band'}} yScale={{ type: 'linear' }}>
        <AnimatedAxis orientation='bottom' />
        <AnimatedAxis orientation='left' />
        <AnimatedGrid columns={false} numTicks={4} />
        <AnimatedLineSeries
          dataKey='Avg Line'
          data={pivotedWeather}
          xAccessor={d => d.date}
          yAccessor={d => d.TMIN}
        />
      </XYChart>
    </div>
  );
```

### Versions of things

- `@visx/xychart@2.11.1`
- `react@18.2.0`
- `react-dom@18.2.0`

Any debugging tips here would be helpful! Everything works like a charm aside from this blip.

**Comment by williaster** [comment]
hey @DingoEatingFuzz 👋  thanks for checking out `visx`. 

it's a bit hard to debug without a codesandbox or similar, but the responsive width should work as long as the parent container has a non-zero width. I'm not sure what `<div className={timeseries}>` is doing in your example, but have you ensured it has a non-zero width? you could add `width: `100%` or an appropriate `flex-grow` if it's in a flex container. if that doesn't work, maybe you can drop this in a sandbox so I can further debug?

> I have seen that if either dimension is 0 then rendering is skipped, which makes sense though resulted in a totally confusing developer experience.

this is a great point, we could definitely add a console warning in this case to give the developer a signal (happy to 👀  a PR if someone else is interested in this!)

**Comment by DingoEatingFuzz** [comment]
The parent element definitely has a width. I tried `100%` as well as a specific `1000px` and no dice. I'll try reproducing in a code sandbox, but since code that worked in a sandbox stopped working once I copy/pasted to my app, I'm afraid this might be a heisenbug situation.

**Comment by DingoEatingFuzz** [comment]
Welp. The plot has thickened.

I tried four scenarios and got these results:

| environment | does it work? |
| --------- | ----- |
| `vite dev` | No |
| `vite build && python -m http.server` | No |
| deploy with Surge | Yes |
| Code Sandbox | Yes |

Furthermore, in those first two localhost scenarios, everything works in Safari and Firefox 😐.

I guess I'll close this, since it seems to be a "my machine" kind of issue. Here's the deployed site for the curious (give it a bit to load; it's doing real weird data stuff and there are no loading states (works in progress, amirite?) https://defiant-wrist.surge.sh/)
