### ISSUE TITLE
bug(text, shape): measurement utils create svgs that screen readers can see

### ISSUE THREAD

**Issue by thomashoggard** [airbnb/visx#1544]
Within the visx-text utility function [getStringWidth](https://github.com/airbnb/visx/blob/42d3213fe5286388fc456eade9b3874d096616aa/packages/visx-text/src/util/getStringWidth.ts), it creates an svg and appends it to the pages body.  Using voiceover on Mac, you can navigate to the svg and it will read out the `text` element to the user.  I think we should add `aria-hidden` to the svg element to prevent it from being picked up.

**Comment by williaster** [comment]
hey @thomashoggard 👋  thanks for highlighting this issue. I agree with your suggested solution, happy to review a PR if someone wants to take a shot at it! 👀

**Comment by williaster** [comment]
noting this is a problem in `@visx/text` (linked above) and probably also in `@visx/shape` where we also have a measurement element https://github.com/airbnb/visx/blob/15e3f8cd33c4df1982a2f70487e367c6fac87d7c/packages/visx-shape/src/util/getOrCreateMeasurementElement.ts

**Comment by thomashoggard** [comment]
I can take a stab at it on Monday if no one gets around to it by then!
