### ISSUE TITLE
XYChart Horizontal xScale issues

### ISSUE THREAD

**Issue by LanceAbuan** [airbnb/visx#1547]
I have a horizontal bar chart in which I want to start from a non-zero point on the X Axis, but when creating an xScale on a Horizontal XYChart, if you set zero: false, there is no change. It works on non-horizontal XYCharts. 

xScale = { type: 'linear', zero: false };

**Comment by williaster** [comment]
Hi @LanceAbuan 👋  thanks for checking out `visx`. can you please repro this with a sandbox?

looks like it works fine to me https://codesandbox.io/s/custom-theme-forked-ukc4lh?file=/Example.tsx

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/4496521/181099827-b754117c-67a0-4ba8-b9a3-407e913e7848.png">

**Comment by williaster** [comment]
ah I think I misread the first time, you want the scale to be e.g., `500-1000`, not `0-1000`?

**Comment by williaster** [comment]
that also seems to work fine, if you can repro that'd be great. https://codesandbox.io/s/custom-theme-forked-jdb6xf?file=/Example.tsx

This seems to be using the minimum value found as the minimum for the scale. if you want more customization beyond that you'd need to specify your own `domain`

<img width="645" alt="image" src="https://user-images.githubusercontent.com/4496521/181100800-9de0af26-13e9-4218-a05d-d139751c2f5b.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/4496521/181100884-83ccd2c9-de5a-46f0-947f-b0e10036585d.png">

**Comment by williaster** [comment]
closing without more info
