### ISSUE TITLE
Visx/zoom react 18 typescript error

### ISSUE THREAD

**Issue by GabriFila** [airbnb/visx#1560]
Hi everyone!

I tried to upgrade a project to React 18 with Typescript, when using the `<Zoom></Zoom>` component I get this TS error:
```
'Zoom' cannot be used as a JSX component.
  Its instance type 'Zoom' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type '{} | null | undefined' is not assignable to type 'ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
          Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props
```

I created a simple [CodeSandbox](https://codesandbox.io/s/bold-monad-nq73of?file=/src/App.tsx) to reproduce the error. The dependencies are the latest ones, both for React and Visx.

Do you have any idea how to solve it?

Thank you!

**Comment by williaster** [comment]
Hi @GabriFila your sandbox references `@vx/zoom` which is now deprecated in favor of `@visx/zoom`. here's an [updated sandbox](https://codesandbox.io/s/elastic-pond-zmtw5b?file=/src/App.tsx).
