### ISSUE TITLE
Airbnb has a major design flaw

### ISSUE THREAD

**Issue by adam-s** [airbnb/visx#1593]
Sorry for posting this here. I use visx professionally and Airbnb hurt me today with a design flaw which needs to be addressed -- it breaks my heart. Please fix this so other people don't get hurt. You are supposed to use technology to improve people's lives.

Steps to recreate bug.

1. Send message to airbnb first host asking if they have decent wifi because I'm a software engineer who works remote
2. Do crime research for that neighborhood and instead look for a host a few miles away
3. Find a different, second, host. Choose dates to stay. Write a message to the second host about myself and why I'm staying.
4. Press the request button

I wake up in the morning to these messages. This is design output. This is the responsibility of the design team at Airbnb to make sure that the end user, me, clearly understands the intent of the messages.

![IMG_5887](https://user-images.githubusercontent.com/232388/198124245-ba394849-4a80-49ac-afca-0c803036a9fd.PNG)

5. Interpret the message: a. My request to stay at second host's property has been accepted. b. Follow the link to pay for the second host's property. When looking at the button to complete the transaction there isn't visible the property information I'm paying for. I assume that I'm paying the for second host's property in Gulfport.
6. Realize that I paid for the first host property which I didn't want
7. Request a cancellation and refund.
8. When denied for a refund, offer $200 immediate loss for a cancellation and refund the difference which is refused.

I'm on the hook for a $2,300 loss having booked two airbnb stays on the same dates. This isn't my fault. The text messages Airbnb sent me are very misleading.

I don't care about the outcome. I'm sure based on the customer support from airbnb your legal team will be very upset if you respond to this. Please forward this to your design team so that other people don't get hurt and needlessly lose $2,300 because of your design flaw. I successfully use visx professionally. If I can't understand a user interface, it means that it has a very serous flaw. Please have empathy for your users.

**Comment by williaster** [comment]
@adam-s please checkout https://www.airbnb.com/help/feedback
