### ISSUE TITLE
Breaking change with ESM requirement for 2.17.0 due to `npm audit fix`

### ISSUE THREAD

**Issue by rj-david** [airbnb/visx#1613]
`npm audit fix` automatically updates some packages to version 2.17.0, which requires ESM. That resulted in builds breaking if ESM is not supported.

Since this is a breaking change, this must be a major update, and therefore version 3 to follow semver?

**Comment by B3none** [comment]
I'm getting the same issue which is preventing the build for my `next 12` application

**Comment by coding-camel** [comment]
Yep, bricks my next 13 app

```
Server Error
require() of ES Module /d3-scale/src/index.js from /@visx/scale/lib/scales/band.js not supported. 
Instead change the require of index.js in /@visx/scale/lib/scales/band.js 
to a dynamic import() which is available in all CommonJS modules.

This error happened while generating the page.
/@visx/scale/lib/scales/band.js (6:16)
/@visx/scale/lib/index.js (28:36)

**Comment by luuk777w** [comment]
Also having this issue

**Comment by theforager** [comment]
Thanks @luuk777w! I was having the same issue, but the overrides worked for me.

**Comment by thomasmost** [comment]
Overrides aren't working for me, for some reason—possibly because I'm using Turborepo? Not sure, but I tried adding it to all my package.json files and still got the error. Just an FYI

**Comment by coding-camel** [comment]
@thomasmost Same for me, but no Turborepo.

Trying again today it works somehow. Only difference being installing the overrides before updating. Deleting `package-lock.json` and `node_modules` may also be worth trying?
