### ISSUE TITLE
require() of ES Module not supported in React/NextJS/TS project with 2.17.0

### ISSUE THREAD

**Issue by thomasmost** [airbnb/visx#1617]
After upgrading to the 2.17.0 libraries, I get the following error:

`Error: require() of ES Module /Users/thomas/my_project/web/node_modules/d3-scale/src/index.js from /Users/thomas/my_project/web/node_modules/@visx/scale/lib/scales/band.js not supported.`

A quick web search suggests downgrading the packages... but surely there must be a better solution to this than effectively ending my ability to patch visx in my project. Advice?

**Comment by williaster** [comment]
duplicates #1613
