### ISSUE TITLE
Cannot find module - React 18, Next 13

### ISSUE THREAD

**Issue by JGalbss** [airbnb/visx#1625]
Started using visx yesterday. Installed with pnpm, but I am having issues with imports. 

`Cannot find module '@visx/scale' or its corresponding type declarations.ts(2307)`

this applies to all modules, but they run fine when in dev. Tried restarting my ts server, deleting and reinstalling modules, installing  types separately. No luck yet. Hoping someone can provide some insight here, thanks!

**Comment by williaster** [comment]
I tried to repro this and could not
