### ISSUE TITLE
Drag elements inside visx/zoom containerRef

### ISSUE THREAD

**Issue by czescwojtek** [airbnb/visx#1632]
I have this interactive graph that I'd like to draw using an SVG. Have set up the `Zoom` component which passes `containerRef` to the `SVGSVGElement` like this:

```
<Zoom<SVGSVGElement> width={width} height={height}>
  {({ containerRef, toString }) => (
    <motion.svg
      className="touch-none"
      width={width}
      height={height}
      ref={containerRef}
    >
      <g transform={toString()}>
          {nodes.value.map((node) => (
            <Node key={node.id} {...node} />
          ))}
      </g>
    </motion.svg>
  )}
</Zoom>
```

Each of the `Node` components you can see above is a `motion` (framer-motion) component set up to be draggable:

```
<motion.circle
  drag
  cx={0}
  cy={0}
  r={10}
  initial={{ x, y }}
  animate={{ x, y }}
  exit={{ opacity: 0 }}
/>
```

The issue here is when I try to drag around any node element, the whole canvas is moving with the cursor: ![Untitled](https://user-images.githubusercontent.com/3768638/212058612-6d16504c-ea78-4cc7-aa6c-caa3cd3c9250.gif)

Is it possible to allow for dragging elements inside the `SVGSVGElement`?

**Comment by FerJSsilva** [comment]
Did you find the solution for this one? Just curious

**Comment by czescwojtek** [comment]
@FerJSsilva Sort of - I mean, I gave up using visx/zoom anyway - due to the high number of rerenders. I implemented d3/zoom by myself
