### ISSUE TITLE
visx/shape documentation missing

### ISSUE THREAD

**Issue by jonambas** [airbnb/visx#1647]
See [https://airbnb.io/visx/docs/shape](https://airbnb.io/visx/docs/shape), and scroll down. 

I'm not crazy right, there's supposed to be more content below the examples?

<img width="1301" alt="Screen Shot 2023-02-03 at 10 32 07 PM" src="https://user-images.githubusercontent.com/3903325/216745897-4b5a8578-6636-4fd5-86c8-11ee25687a9b.png">

**Comment by williaster** [comment]
Thanks @jonambas for the report and the fix! this is broken for a couple of packages from a refactor we (I) did. I'm super slammed this week but will review ASAP. Will take more comments to your PR! 🙌
