### ISSUE TITLE
Pattern lines Not rendering on Firefox version 91.6.0esr

### ISSUE THREAD

**Issue by gauravarora20** [airbnb/visx#1650]
A very basic pattern line in a bar chart is not showing up in Firefox version 91.6.0esr

Could someone please update any possible solution or confirm that this browser/version isn't supported at the moment?

**Comment by hshoff** [comment]
Hi @gauravarora20, I downloaded Firefox `91.6.0esr` and was able to visit https://airbnb.io/visx/patterns without issue. Could you share a code example/[codesandbox](https://codesandbox.io) reproducing the problem?

**Comment by hshoff** [comment]
Hi @gauravarora20 closing this as we haven't heard back. Happy to reopen if needed.
