### ISSUE TITLE
`@visx/visx` missing v3.0.0 release on npmjs

### ISSUE THREAD

**Issue by claudious96** [airbnb/visx#1651]
Hi, really loving this library, thanks for the effort in making the use of d3 more react friendly.

I noticed that on January 6th v3.0.0 has been released, in the github repo the umbrella package `@visx/visx` seems to have upgraded all the dependencies to the newest v3 but on [npm](https://www.npmjs.com/package/@visx/visx) the 3.0.0 release is missing and therefore running `npm install @visx/visx` will result in installing version 2.18.0 .

**Comment by williaster** [comment]
thanks for highlighting this, it's fixed now with a `3.0.1` https://www.npmjs.com/package/@visx/visx/v/3.0.1

<img width="355" alt="image" src="https://user-images.githubusercontent.com/4496521/219792640-669c66d2-b49c-416d-9739-3ace68dd46fa.png">
