### ISSUE TITLE
`@visx/scale` has an incorrect package.json that always resolve to cjs file

### ISSUE THREAD

**Issue by MarkLyck** [airbnb/visx#1653]
I'm getting the following error when trying to run a unit test of a component that has a visx chart in it.

```
Error: require() of ES Module /.../node_modules/.pnpm/d3-scale@4.0.2/node_modules/d3-scale/src/index.js from /.../node_modules/.pnpm/@visx+scale@3.0.0/node_modules/@visx/scale/lib/scales/band.js not supported.
Instead change the require of index.js in /.../node_modules/.pnpm/@visx+scale@3.0.0/node_modules/@visx/scale/lib/scales/band.js to a dynamic import() which is available in all CommonJS modules.
```

I found some one else with the same issue here: https://github.com/vitest-dev/vitest/issues/2742

This is happening because the `@visx/scale` package has an incorrect package.json that always resolves it to a .cjs file, when it should be resolving to esm for unit tests.

Also see: https://github.com/vitest-dev/vitest/issues/2742#issuecomment-1406223702

There is a "workaround" for those using `vitest.config.ts` but my vitest config is in my vite config, and I have not found a way to make it work in there. Please comment if you know of a workaround that works in that file.

Or hopefully just get the root problem resolved so we don't have to override the imports.

**Comment by Matsebassen** [comment]
Same issue here as well

**Comment by Matsebassen** [comment]
I downgraded to 2.X.X version of Visx, which seems to work fine. The functionality I use is still available here, but I will upgrade to version 3 when this is fixed.

**Comment by williaster** [comment]
thanks for raising this, it partially duplicates https://github.com/airbnb/visx/issues/1637 but I think there are two distinct issues:
1) a problem with our package.json incorrectly pointing to esm/cjs
2) the broader question of whether we can even support cjs because of the esm-only d3 packages added in the `3.0.0`

so let's track the former with this issue. I am hoping this can be resolved by updating to the following syntax per package as suggested by @diginikkari 

```
"exports": {
    ".": {
        "import":"./esm/index.js", 
        "require": "./lib/index.js"
    }
  },
```

anyone agree/disagree? I have been absolutely slammed at work so haven't had a chance to try this. is anyone interested in updating all the packages to this syntax? I'd be happy to review a PR and we can do a pre-release to test it.

**Comment by sametcodes** [comment]
@williaster I'm getting the same issue with `@visx/shape` package and added up the configuration of the export to its package.json. But I'm still getting the same issue.

> Error [ERR_REQUIRE_ESM]: require() of ES Module ~/node_modules/d3-scale/src/index.js from ~/node_modules/@visx/scale/lib/scales/band.js not supported.

**Comment by elliothershberg** [comment]
Experienced the same issue with 3.x packages, and also downgraded to 2.x packages for the time being.

@williaster because the proposed change to the exports didn't work (cc @sametcodes), do you have thoughts on how you want to proceed? Would dropping CJS support solve this?

**Comment by miquelvir** [comment]
Same issue....

**Comment by LZL0** [comment]
Same here.

**Comment by marcodenic** [comment]
Getting this issue today, fix planned?

**Comment by elliothershberg** [comment]
@williaster I'm willing to dedicate time to helping to fix this—visx is useful across many of my projects. What do you think the best path forward is to solve this?

**Comment by williaster** [comment]
thanks @elliothershberg 🙏 I think the fix we are in most favor of is described here https://github.com/airbnb/visx/issues/1637#issuecomment-1536757078

maybe we can move collab discussion there? it's potentially non-trivial (as it involves new packages) but happy to discuss if you're up for it! ❤️

**Comment by LZL0** [comment]
This should def work out-of-the-box. NextJS is the most popular React framework out there.

**Comment by williaster** [comment]
alright I think this is fixed folks. try `3.2.0` and let me know if you have issues, see https://github.com/airbnb/visx/pull/1716 where we introduced `@visx/vendor` for more details.

related comment here https://github.com/airbnb/visx/issues/1637#issuecomment-1612412243

**Comment by williaster** [comment]
I'm going to go ahead and close this, but please post any issues you have/we can re-open if necessary.

**Comment by elliothershberg** [comment]
@williaster you are a rock star 🙏 

Just upgraded my visx dependencies with no problems! If there are other blockers/bugs, I'll try to be more prompt in helping out with a bug fix next time.

**Comment by williaster** [comment]
happy to hear!
