### ISSUE TITLE
XYChart: Tooltip snapping does not work for stacked area/bars

### ISSUE THREAD

**Issue by Kenny806** [airbnb/visx#1667]
**Description:**
When using `BarStack` or `AreaStack` together with `Tooltip`, the snapping does not work despite setting the `snapTooltipToDatumX/Y` props correctly. This is reproducible in https://airbnb.io/visx/xychart when choosing either area stack or bar stack. 

**Cause:**
I did a bit of digging and found that the issue is caused by having two different datum types when using `AreaStack` or `BarStack`. The two components transform the input data to `BarStackDatum<XScale, YScale>` or `AreaStackDatum` respectively, also storing them in the dataRegistry in this format and updating the accessors accordingly. However, the `nearestDatum` property in `TooltipContext` has the format of the original data and the `Tooltip` component then attempts to apply the accessors (made for `BarStackDatum` or `AreaStackDatum`) to the original data format, which does not return any value. 

**Possible solution:**
A solution could be in the `findNearestStackDatum` util, where the nearest datum is extracted from the original data. By extracting the datum from dataRegistry instead of the original data, the `nearestDatum` in `TooltipContext` will be in a format that the accessors can actually read.

I created a PR: #1668 . But I'm not very familiar with the code base so it could easily break something I'm not aware of.

**Workaround:**
It is possible to get around this issue by using a hook that calls `TooltipContext`'s `updateTooltip` with the desired 'snapped' values for `tooltipTop` and/or `tooltipLeft` whenever the position is updated. Probably not very good for performance and also duplicates most of `Tooltip`'s snapping logic with only minor changes.

**Comment by williaster** [comment]
Hey @Kenny806 thanks for reporting this and opening the linked PR. This issue duplicates https://github.com/airbnb/visx/issues/1533 so I'm going to close to consolidate. 

You're right about the root cause (thanks for doing the work of digging!) – and there was an alternative approach to fix it discussed on that thread so maybe we can circle back there for the ideal approach?
