### ISSUE TITLE
@visx/xychart AnimatedLineSeries does not animate

### ISSUE THREAD

**Issue by SolutionsEngineer** [airbnb/visx#1670]
Hi,

I've been implementing a simple XY line chart and faced an issue with `AnimatedLineSeries`. 
The problem is that using the `AnimatedLineSeries` component does not result in an animated line, but gives the same result as using the `LineSeries` component. 

The issue can be checked on the official documentation site: https://airbnb.io/visx/xychart

Is there some workaround to make the line series animated?

**Comment by williaster** [comment]
Hi, can you be more specific? all of these transitions are animated. Uncheck "use animated components" to compare. 

![animation](https://user-images.githubusercontent.com/4496521/223804660-633cbb2c-5907-4fff-a0f0-4309233cc906.gif)

**Comment by williaster** [comment]
Going to close this

**Comment by SolutionsEngineer** [comment]
Sorry, I should be more precise about it. I meant that the initial animation works only for the axis, not the line.  I'm sending the behavior of the bar series and the line series. Notice the difference in the rendering. The bar series appears with the animation while the line series pops out ready.
![chrome_QQsSmAATKh](https://user-images.githubusercontent.com/106707979/224834908-a638e46f-ff9b-411c-bdc4-c581d8c685c1.gif)
