### ISSUE TITLE
Linear scale requires non-zero domain (bar chart with all zeros looks wrong)

### ISSUE THREAD

**Issue by ls-andrew-borstein** [airbnb/visx#1671]
I'm not sure if this is a bug or a known issue and would be happy for clarification on that. 

### Example with 0s for all data

When creating a [bar chart](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-bars?file=/Example.tsx) with a linear y scale, a data set with all zero values will render all bars appearing as 50% of graph height. 

https://codesandbox.io/s/visx-bar-chart-all-zero-values-xysylg?file=/Example.tsx

![Screen Shot 2023-03-15 at 12 26 18 PM](https://user-images.githubusercontent.com/82463438/225378887-a61c94a1-f947-403c-bd53-85a0314697b6.png)

### Example with 0s for all data + non-zero domain max

But if I manually change the max domain value from 0 to 1, the chart shows the correct visualization where all bars have 0 height. 

https://codesandbox.io/s/visx-bar-chart-all-zero-values-non-zero-domain-zb2q3m?file=/Example.tsx:1266-1288

![Screen Shot 2023-03-15 at 12 42 49 PM](https://user-images.githubusercontent.com/82463438/225380271-edc16f10-a451-4361-a075-be1b5e792ec1.png)

Based on what I'm seeing in [the D3 docs](https://github.com/d3/d3-scale/blob/main/README.md#scaleLinear), the default value for a range is `[0, 1]` so it seems like `[0, 0]` would be invalid. I'm not super familiar with d3 so I can't tell if this is a bug with their code, or just a mismatch in expectations. 

I didn't see anything in the visx docs or previous issues about protecting against this scenario, e.g. changing 

```tsx
domain: [0, Math.max(...data.map(getLetterFrequency))],
```

to 

```tsx
domain: [0, Math.max(...data.map(getLetterFrequency)) || 1],
```

Any advice on this? 

***

Update: changing the domain to `[0,1]` also changes the y-axis in a kind of weird way (I would expect to see an axis scale of 0 in this case, not 0 to 1), so this might not be an ideal fix. Regardless, it still seems like visx should be prepared to deal with all 0 values somehow, even that just means some documentation guidance.

**Comment by williaster** [comment]
Hey @ls-andrew-borstein thanks for checking out `visx`. 

I think this duplicates https://github.com/airbnb/visx/issues/473 which links to a couple other issues as well, so I'm going to close this but feel free to re-open if there's something that' unresolved. tl;dr it is due to d3 logic.
