### ISSUE TITLE
showSeriesGlyphs is not proper show in xychart 

### ISSUE THREAD

**Issue by AjayGol** [airbnb/visx#1675]
![Screenshot 2023-03-21 at 4 43 29 PM](https://user-images.githubusercontent.com/77920960/226589777-89844b53-335e-4f98-bcf5-312dc56112f9.png)
Here is Image not proper show dot circle.

**Comment by williaster** [comment]
can you provide more information about your browser and/or link to an example where you see this? 

this is a fully stand-alone example where it works, so if we can't repro I'd close this issue.
https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-xychart

**Comment by AjayGol** [comment]
okay i will send you

**Comment by williaster** [comment]
closing without more info
