### ISSUE TITLE
[scale] make scales immutable

### ISSUE THREAD

**Issue by hshoff** [airbnb/visx#170]

**Comment by trainorpj** [comment]
I'm interested in this (either learning about it or working on it), although I'm not sure where one would start.

I assume one could use immutable.js, but that seems like a "big hammer, small nail" solution... is there a preferable alternative?

**Comment by techniq** [comment]
I'm curious what the goal for this is.  I recently [ported](https://github.com/react-tools/react-move/issues/31#issuecomment-337437595) 2 d3 examples using vx and react-move to tween the domain and range of some scales.  It has some mobile performance problems though, and was curious if this could potential improve it (although i am only using d3-scales and not vx-scales in those examples)

**Comment by williaster** [comment]
I think some of the thinking here was that currently when you update a d3 scale, you don't get a copy, you mutate the _original_ scale. however, in the React world you often depend on immutability, for example in order to trigger a component to update upon a prop change. in general I think immutability makes caching and change detection techniques more simple / less buggy.

in terms of implementation I think there were a few thoughts
- you could wrap the d3 scale object, wrapping any mutation calls in a `scale.copy()` 
- you could have a helper like
```js
function updateScale(scale, { ...args }) {
  const nextScale = scale.copy();
  Object.keys(args).forEach((key) => {
    if (nextScale.hasOwnProperty(key)) nextScale[key](args[key])
  });
  return nextScale;
}
```
- or you @nelgau had an interesting thought about component-izing scales like `<Scale type="time" />`

**Comment by hshoff** [comment]
There's an `updateScale()` helper in @vx/scale already https://github.com/hshoff/vx/blob/master/packages/vx-scale/src/util/updateScale.js I forgot I added that way back in May and haven't used it yet. 

```js
shouldComponentUpdate(nextProps, nextState) {
  const { xScale } = this.props;
  return compareScale(xScale, nextProps.xScale); // return true if scales are different, false otherwise

  // or even something like
  return xScale.uid !== nextProps.xScale.uid;
}
```

Just some ideas. More to think about here...

**Comment by toughyear** [comment]
@hshoff  is there a sample implementation of updateScale() ? I tried switching between two different domains for the same scale when a button is pressed. 

```javascript
//x scale
  const xScale = scaleLinear({
    domain: [
      _.minBy(data, function (o) {
        return o[config.xAxisCol];
      })[config.xAxisCol],

      _.maxBy(data, function (o) {
        return o[config.xAxisCol];
      })[config.xAxisCol],
    ],
    range: [0, InnerWidth],
    nice: true,
  });'
  // animating the scatterchart
  const [chartZoom, setChartZoom] = useState(true);

  useEffect(() => {
    if (chartZoom) {
      // set scale to zoom
      updateScale(xScale, {
        domain: [
          Math.min(
            0,
            _.minBy(data, function (o) {
              return o[config.xAxisCol];
            })[config.xAxisCol]
          ),

          _.maxBy(data, function (o) {
            return o[config.xAxisCol];
          })[config.xAxisCol],
        ],
      });
    }
  }, [chartZoom]);
```

It doesn't seem to affect the scaling (the axis that uses the scale does not change at all).

**Comment by kristw** [comment]
Is this issue still relevant?

**Comment by williaster** [comment]
this one is super old. maybe can close and reopen if there is interest.
