### ISSUE TITLE
I want to create many to many relationship in the trees

### ISSUE THREAD

**Issue by asha-c-r-123** [airbnb/visx#1707]
I want  to map the nodes like one children can have multiple parent nodes and same 1 parent can multiple childrens, please provide the examples for this requirement .

Thanks,

**Comment by williaster** [comment]
Hey @asha-c-r-123 I'm going to defer to the [`d3-hierarchy` docs](https://github.com/d3/d3-hierarchy) on this one. Generally you cannot do this as discussed in this issue https://github.com/d3/d3-hierarchy/issues/152
