### ISSUE TITLE
For Brush and selectedBrushStyle, the border around the Brush does not appear

### ISSUE THREAD

**Issue by tturnerswdev33** [airbnb/visx#1712]
I have the Brush showing up along with the handles and I can change the color of the PatternLines using accent color, but the border around the Brush is not there no matter what I set colors to.  Is there some trick to that?

My settings are:
  const brushMargin = { top: 10, bottom: 15, left: 50, right: 20 }
  const chartSeparation = 30
  const PATTERN_ID = 'brush_pattern'
  const GRADIENT_ID = 'brush_gradient'
  const accentColor = 'red' // color of pattern slants 
  const background = '#584153' // dark purple
  const background2 = '#af8baf' // light purple
  const selectedBrushStyle = {
    fill: `url(#${PATTERN_ID})`,
    stroke: 'red',  
    strokeWidth: 2 // does nothing
  }
I tried to set brush style and accent to RED to make it stand out. The fill cross hatch lines show up red but there is no box at all around the Brush.
<img width="733" alt="Screen Shot 2023-06-13 at 8 26 11 AM" src="https://github.com/airbnb/visx/assets/122304631/29f8014a-315b-4f0b-9fb4-31ddecd4d146">

**Comment by williaster** [comment]
Hi @tturnerswdev33, can you link to a reproducible example of this? the [gallery version](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-brush?file=/Example.tsx) works just fine so I'm not sure what's going on in your case

<img width="385" alt="image" src="https://github.com/airbnb/visx/assets/4496521/f35e17f7-aaa4-4277-aaa2-0593e0ad8218">

**Comment by hshoff** [comment]
Confirmed works without issue in the gallery version. Closing for now, happy to reopen if need be.
