### ISSUE TITLE
Issue with Visx ParentSize component 

### ISSUE THREAD

**Issue by FabioDainese** [airbnb/visx#1729]
Hi guys! In my NextJS (v13.4.8) project I'm currently using the Visx [ParentSize](https://airbnb.io/visx/docs/responsive#:~:text=the%20chartToRender%20somewhere-,ParentSize,You%20might%20do%20the%20same%20thing%20using%20the%20ParentSize%20component.,-Example%3A) component in order to make my graph responsive, but this seems to generate a console error (`Error: <rect> attribute width: A negative value is not valid. ("-40")`).

Basically, I'm using the `width` and `height` props that the `<ParentSize />` component offers, but at the first render those are equals to `0`, ultimately making the `<Bar ... />` component having negative values and thus generating the errors.

Just to give you a better picture, here's how I've setup my component that uses Visx:

```javascript
"use client"

// ... Visx imports 

const BarChart = () => {
        return (
            // ... other divs, etc.
            <div className="... relative">
                <ParentSize debounceTime={50}>
                    {({ width, height, top, left, ref, resize }) => (
                        <CustomChart width={width} height={height} />
                    )}
                </ParentSize>
            </div>
        );
};

const CustomChart = ({ width, height }) => {
    // define margins from where to start drawing the chart
    const margin = { top: 0, right: 0, bottom: 40, left: 40 };
    // defining inner measurements
    const innerWidth = width - margin.left - margin.right;
    const innerHeight = height - margin.top - margin.bottom;

    return (
        <svg width={width} height={height}>
            <Group left={margin.left} top={margin.top}>
                <Bar
                    x={0}
                    y={0}
                    width={innerWidth}
                    height={innerHeight}
                />
            </Group>
        </svg>
    );
};

export default BarChart;
```

Am I using the `<ParentSize />` component improperly? or am I missing something?

Here's instead the full project in a [sandbox](https://codesandbox.io/p/sandbox/visx-bar-error-45tqxr) (if you then run the project and inspect the page you will see the error)

P.S. tbh in my real project I'm not really making a black rectangle, but I'm using this kind of setup for handling a tooltip. This is just the minimal way to reproduce the issue.

**Comment by williaster** [comment]
hey @FabioDainese , typically with this component you need to check for `0` width and not render that frame. alternatively you can set a default `width` (setting this meaningfully is hard, though). 

this happens because the `ref` + `useCallback` used to measure the parent element isn't called until after the first render, so the initial value of `0` is passed through.

**Comment by FabioDainese** [comment]
Ah, now it makes much more sense! Thank you so much @williaster you really made my day 🙌

Just for completeness - and in case someone stumbled on the same doubt - here's the solution that I've implemented (based on the [previous](https://github.com/airbnb/visx/issues/1729#issuecomment-1624016227) suggestion)

```javascript
// ... same code as before

const CustomChart = ({ width, height }) => {
    if(width === 0 | height === 0) {
        return null
    }

    // ... same code as before
};
```
