### ISSUE TITLE
Xychart package: tooltip is not snapped on stacked areas

### ISSUE THREAD

**Issue by eponae** [airbnb/visx#1740]
SnapTooltipToDatumX and snapTooltipToDatumY do not seem to work on stacked areas, but it's working on regular charts.
Is it something that still needs to be implemented, or it's not supposed to be implemented?

For example, on the documentation demo, for "area stack" https://airbnb.io/visx/xychart, there is no dot on the lines, and the snap animation does not appear. The "snap" options are disabled.

![Screenshot 2023-08-09 at 10 13 47](https://github.com/airbnb/visx/assets/6737423/00fe9850-a886-4c7c-a813-f2898f56086c)

I appreciate your help.

**Comment by chromodome** [comment]
Yep, seems this is not implemented. I was pulling my hair out trying to figure out why it wasn't working until i realized that stacked groups don't support this.

**Comment by williaster** [comment]
thanks for opening this, noting that it duplicates https://github.com/airbnb/visx/issues/1533, so I will close this one for a single point of tracking

**Comment by eponae** [comment]
thank you 👍
