### ISSUE TITLE
XYChart - remove empty values from x axis / custom xscale range/domain breaks axis 

### ISSUE THREAD

**Issue by zebapy** [airbnb/visx#1743]
I'm trying to replicate the chart on the left but using XYChart (right). Whenever i pass custom range and domain to the xScale prop on the XYChart, it appears to mess up the bottom axis. 

Repro https://codesandbox.io/p/sandbox/visx-chart-hide-empty-6kvlwj

![image](https://github.com/airbnb/visx/assets/2199845/a3bd3eed-737e-4267-8ef4-9b70f6ceb881)

```tsx
import React from "react";
import { scaleLinear } from "@visx/scale";
import { LinePath } from "@visx/shape";
import { AxisBottom, AxisLeft } from "@visx/axis";
import { extent, max } from "d3-array";
import { XYChart, LineSeries, Axis } from "@visx/xychart";

import data from "./data.json";

const datasets = [data.age.positives, data.age.candidates];

// Find the overall extent of x and y values across all datasets
const allData = datasets.flat();
const xExtent = extent(allData, (d) => d.x);
const yMax = max(allData, (d) => d.y) ?? 0;

// Create the x-scale using the xExtent
const xScale = scaleLinear({
  domain: [xExtent[0] ?? 0, xExtent[1] ?? 0],
  range: [0, 200],
});

// Create a shared y-scale using the overall maximum y value
const yScale = scaleLinear({
  domain: [0, yMax],
  range: [200, 0],
});

const LineChart = ({ width, height }) => (
  <svg
    width={width}
    height={height}
    style={{
      margin: 100,
      overflow: "visible",
    }}
  >
    {/* Draw lines for each dataset */}
    {datasets.map((dataset, datasetIndex) => (
      <LinePath
        key={datasetIndex}
        data={dataset}
        x={(d) => xScale(d.x)}
        y={(d) => yScale(d.y)}
        stroke="black"
        strokeWidth={2}
      />
    ))}

    <AxisBottom scale={xScale} top={200} />
    <AxisLeft scale={yScale} left={0} />
  </svg>
);

const AltChart = ({ width, height }) => (
  <XYChart
    width={width}
    height={height}
    xScale={{
      type: "linear",
      domain: [xExtent[0] ?? 0, xExtent[1] ?? 0],
      range: [0, 200],
    }}
    yScale={{ type: "linear" }}
    margin={{ top: 40, bottom: 40, left: 40, right: 40 }}
  >
    {datasets.map((dataset, datasetIndex) => (
      <LineSeries
        key={datasetIndex}
        data={dataset}
        dataKey={String(datasetIndex)}
        xAccessor={(d) => d.x}
        yAccessor={(d) => d.y}
        stroke="black"
        strokeWidth={2}
      />
    ))}
    <Axis orientation="bottom" />
    <Axis orientation="left" />
  </XYChart>
);

const App = () => (
  <div>
    <LineChart width={400} height={400} />
    <AltChart width={400} height={400} />
  </div>
);

export default App;
```

**Comment by williaster** [comment]
Hi @zebapy thanks for checking out visx. You codesandbox doesn't load for me but I would guess this would work if you removed both the `domain/range` in your `xychart` `xScale` config (I think the main problem is your range override which doesn't account for the margin. the chart will compute this for you so I'd just remove it)

**Comment by zebapy** [comment]
Hi @williaster  thanks for fast reply. Does sandbox load now?

If i remove the domain/range, then I get a gap of empty data from 0-50 on the axis. I don't want them to show up if there's no data. 

Desired (non xychart)
<img width="272" alt="image" src="https://github.com/airbnb/visx/assets/2199845/bb7c6aa1-9305-4448-85b8-8c83dd831a12">
Result without domain/range on xScale prop
<img width="377" alt="image" src="https://github.com/airbnb/visx/assets/2199845/0c2d8cd3-4e5d-4efd-88c3-8083cf686d69">

**Comment by williaster** [comment]
Ah yes, this is because we include `0` in linear scale domains by default (this is mostly for `y-axis` where we feel this is best practice), so you can set `zero: false` to opt out. 

Here's a working forked version https://codesandbox.io/p/sandbox/visx-chart-hide-empty-forked-hfplrt?file=/src/App.tsx

<img width="1348" alt="image" src="https://github.com/airbnb/visx/assets/4496521/a729e773-ecd7-446c-ae96-1d30c7967cee">

**Comment by zebapy** [comment]
apologies for glazing over that param 🤦  tyvm

**Comment by williaster** [comment]
no problem :)
