### ISSUE TITLE
Accessing the scale of an xy chart

### ISSUE THREAD

**Issue by mn-prp** [airbnb/visx#1757]
I'm creating an XYChart with a band scale for the x axis and a linear scale for the y axis, and my use case has led me to two questions: 

1. Can I color the bars based on the linear (y) scale? I assume I'd need to use the `colorAccessor` property, but I don't see an obvious way to introspect into the actual range the chart is using to construct the axis. Is that possible?
2. Relatedly, perhaps, I'd like to reuse this color information on another part of the component...Is it possible to access this linear scale via a hook or something?

I'm sure I can drop down to a lower level and just create my own bar chart, but I'd like to use out-of-the-box simplicity of the XYChart first if possible. Thanks.

**Comment by Kongkille** [comment]
If I understand your issue correctly, you can achieve this using this DataContext

```
import { DataContext } from "@visx/xychart";
import { useContext } from "react";

// in React component
const { xScale, yScale } = useContext(DataContext) || {};
```
[There's some documentation in the Readme at the specific package](https://github.com/airbnb/visx/blob/master/packages/visx-xychart/README.md#advanced-usage)

**Comment by mn-prp** [comment]
Thank you, that is helpful. The documentation there is pretty sparse, but maybe that just means it's time for a PR :)
