### ISSUE TITLE
Adding node version into .npmrc files

### ISSUE THREAD

**Issue by sleonia** [airbnb/visx#1793]
Hi. What do you think about adding a node version into the `.npmrc` files? I've encountered many tooling errors when trying to run yarn build locally or in github codespaces. Based on my experience, only node `16.x.x` is suitable for development, not 17, 18 or 20. Therefore, I believe that adding the node version into `.npmrc` could be beneficial for future contributors.

- [Log of running `yarn type`](https://imgur.com/JOfbDHw)
- [Log of running `yarn dev` inside visx-demo](https://imgur.com/mBqHkU4)

Helpful stackoverflow answer about `yarn dev` issue – https://stackoverflow.com/a/69637053

**Comment by williaster** [comment]
Hey @sleonia, thanks for the suggestion and sorry you had issues yourself when developing. I agree this would be a great addition for future developers. If you (or someone else) is interested in add this I'd happily review!
