### ISSUE TITLE
XYChart forces me to have the yScale include 0

### ISSUE THREAD

**Issue by samnoyes** [airbnb/visx#1795]
Hi, I have been trying to get my chart to look exactly how I want it and I am having some difficulty because there is something wrong with the domain in yScale. When I set yScale on my XYChart to `yScale={{ type: 'linear', domain: [50,100] }}`, it doesn't respect the lower bound. It simply displays 0-100 on the y axis. Now if the domain includes 0 e.g. [-50, 50], then it works as expected. It just forces me to include 0. What am I missing?

**Comment by samnoyes** [comment]
Figured it out. Set `zero: false` in the yScale. Would be great to have this better documented.

**Comment by zzincist** [comment]
took awhile for me to find this too. thanks for finding it!
