### ISSUE TITLE
onBrushEnd infinite render loop

### ISSUE THREAD

**Issue by balbany** [airbnb/visx#1819]
Looks like `@visx/brush` has an infinite render loop bug (when used with `useWindowMoveEvents`).

To reproduce:
- Using the standard brush example from the docs, repoint the `onBrushChange` handler to be triggered by `onBrushEnd`. 
- Now change the brush position more than once in quick succession. You should get the below error:
![image](https://github.com/airbnb/visx/assets/8235277/81dc96d5-f2e9-4104-a77d-d90e6636f452)

Sounds similar to #1283 (due to the involvement of `useWindowMoveEvents`).

Thanks 🙏

**Comment by hshoff** [comment]
Hi @balbany, this seems fixed now. Can see it working here on my fork of the example here: https://codesandbox.io/p/sandbox/vigilant-edison-p9pzjv?file=%2FExample.tsx%3A215%2C1-216%2C1
