### ISSUE TITLE
Typescript React 18 type issue ParentSize

### ISSUE THREAD

**Issue by peterwiebe** [airbnb/visx#1824]
Getting the following error after upgrading to React 18:

```
'ParentSize' cannot be used as a JSX component.
  Its type '({ className, children, debounceTime, ignoreDimensions, parentSizeStyles, enableDebounceLeadingCall, ...restProps }: ParentSizeProps & Omit<HTMLAttributes<HTMLDivElement>, keyof ParentSizeProps>) => Element' is not a valid JSX element type.ts(2786)
```
curious if anyone else has come across this issue and if they did, how did you solve it?

**Comment by hshoff** [comment]
Hi @peterwiebe how are you importing ParentSize? It's the default export https://github.com/airbnb/visx/blob/master/packages/visx-responsive/src/components/ParentSize.tsx

**Comment by hshoff** [comment]
Hi @peterwiebe, going to close this as we haven't heard back. Happy to reopen if needed.
