### ISSUE TITLE
useTooltipInPortal losing position when parent is moved with CSS translate

### ISSUE THREAD

**Issue by valtism** [airbnb/visx#1857]
**Issue:** When I move a chart's parent using CSS transform, the tooltip believes that the chart is in the original position, despite it having moved

**Expected:** The tooltip adjust position to anchor against the moving parent container, like it does on scroll.

**Reproduction:** https://stackblitz.com/~/github.com/valtism/visx-tooltip-repro

Note: The charts here are draggable with `react-grid-layout` that moves each item with CSS transform.

**Video:** 

https://github.com/airbnb/visx/assets/1286001/e2bb429e-0028-44ea-b447-c5d2ea56cef2

**Comment by SheaJanke** [comment]
This seems to be a duplicate of #983. You need to call `forceRefreshBounds()` whenever the tooltip becomes visible. See #1045 for an example of how this was implemented in the xychart package.

**Comment by valtism** [comment]
@SheaJanke Oh wow that's embarrassing to have gone through all this years ago and totally forgotten it all. Thanks for digging this up again for me.
