### ISSUE TITLE
Bar with negative labels below the bar

### ISSUE THREAD

**Issue by sandeeepgithub** [airbnb/visx#1882]
I want to create something like this. 

![image](https://github.com/user-attachments/assets/b2c369fe-f08f-45ef-8a63-f2e339da7069)

But seems like there is lack of documentation. I have somehow reached here, but some of the things seems like a hack instead of concrete one. 

![image](https://github.com/user-attachments/assets/50406f02-2fa3-46ed-878b-14b2de03764b)

Here are the issues I faced: 

1.  How to bring label be at bottom of bar for negative values ?
2. How to add year aligned with the bar, as in the above screenshot  ?
3. How to remove the tick values from the bottom of bar? 

[https://codesandbox.io/p/sandbox/j53vmm](https://codesandbox.io/p/sandbox/j53vmm)

**Comment by govind-io** [comment]
Here is a working codepen with the design that you mentioned along with all the fixes, you can adjusted the color of negative bars as per your convinience.

Code Pen [Link](https://codesandbox.io/p/sandbox/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-bars).

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/72d971fc-0f05-41a3-b9ff-40ec89c1bf39">

**Comment by sandeeepgithub** [comment]
This works @govind-io
