### ISSUE TITLE
Missing documentation for Shape.Pie

### ISSUE THREAD

**Issue by SamSamskies** [airbnb/visx#277]
There is a Shape.Pie component example in the gallery, but there's no documentation for it.

Pie example in gallery: https://vx-demo.now.sh/pies
Shapes documentation: https://vx-demo.now.sh/static/docs/vx-shape.html

**Comment by yuchi** [comment]
@hshoff I may have few minutes off to cover this. Any objections?

**Comment by hshoff** [comment]
@yuchi go for it!

**Comment by casramsey** [comment]
@yuchi - are there any examples anywhere that show how to colour segments and what centroid does, etc?  Been scouring the interweb and can't find anything apart from the example in the gallers.
Thanks kindly

**Comment by yuchi** [comment]
@casramsey you can easily do that by passing a function to the `fill` prop. A good idea is to use a [`scale*` function](http://localhost:3000/legends).

**Comment by casramsey** [comment]
Great help @yuchi - thanks very much!
