### ISSUE TITLE
Zoom and pan of areaChart

### ISSUE THREAD

**Issue by magdalko** [airbnb/visx#361]
Hi,

I have found the zoom and pan in the example: https://codesandbox.io/s/32j6874rx5
I know its still during creation, but using the example I built my zoom and pan: https://codesandbox.io/s/7jp5j920zq
the ideal version of the graph suggests to have only xAxis zoom and pan, like here: https://demos.telerik.com/kendo-ui/bar-charts/pan-and-zoom
Any ideas how I can do it? I try to figure out how it works and how to do it :D

**Comment by s-hood** [comment]
Anyone made progress on this?

**Comment by hshoff** [comment]
Should be possible now with `@visx/brush`. Example: https://airbnb.io/visx/brush
