### ISSUE TITLE
Lines not using crispEdges show up fuzzy on non-retina screens

### ISSUE THREAD

**Issue by kmiyashiro** [airbnb/visx#656]
I'm using a windows machine to develop and I noticed that the lines in vx were fuzzy. I found [this explanation](https://stackoverflow.com/questions/34229483/why-is-my-svg-line-blurry-or-2px-in-height-when-i-specified-1px/34229584), which seems to be correct.

Expand images to see sharpness of bottom axis:
## Current
![current](https://user-images.githubusercontent.com/71852/77245080-1c97b100-6bd9-11ea-8c70-6cc995bf0123.jpg)

## With `shape-rendering="crispEdges"` on `line` or parent `g`
![crisp-edges](https://user-images.githubusercontent.com/71852/77245093-48b33200-6bd9-11ea-9e17-374ac6779645.jpg)

Would you be open to adding `shape-rendering="crispEdges"` for lines? The only downside to using `crispEdges` is that it produces sharp edges even for rounded objects. The `Line` and `Axis` components currently don't make rounded shapes, so I think adding it to those will be safe at least.

**Comment by williaster** [comment]
This seems like a reasonable change to me, happy to review a PR!

**Comment by ArvinH** [comment]
Hi, may I work on this one? trying to get to know more about this tool :)

**Comment by kmiyashiro** [comment]
Hey @ArvinH I actually just worked on this last night, you can review the PR here: https://github.com/airbnb/visx/pull/840

**Comment by kmiyashiro** [comment]
Fixed in #840

**Comment by jbanulso** [comment]
Hi, this change introduced in #840 is causing dotted lines not to be displayed. I achieve the dotted line effect with a rounded line cap (`stroke-linecap: round`), which is the CSS property that causes the problem. An example of how I'm implementing the lines:
```
import { Line as VxLine } from '@visx/shape';

const Line = styled(VxLine)`
  stroke: black;
  stroke-linecap: round;
  stroke-dasharray: 0, 2;
  stroke-dashoffset: 1;
`;

return <Line from={{ x: 0, y: 0 }} to={{ x: 50, y: 0 }} />
```

It seems like it is a browser rendering issue though - I've tested both in Chrome and Firefox and the lines are displayed when increasing/decreasing the zoom level, which leads me to think that there is some sort of bug on the implementation of the `sharp-rendering` attribute.

I can make the lines be displayed with `stroke-linecap: square`, but then the dotted effect is not the desired one. Would you consider reverting this change, as it introduces an unwanted behaviour?

**Comment by hshoff** [comment]
Hi @jbanulso, for now the work around would be to set `shape-rendering: auto;` on the line. This resets [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) to the default value by overriding the previous value. 

```diff
<Line
  from={{ x: x1, y: y1 }}
  to={{ x: x2, y: y2 }}
+ shapeRendering="auto"
/>
```

**Comment by jbanulso** [comment]
Hi @hshoff, that will do it, thank you for the quick answer. And thank you for the great work with this library, it's great to see the progress over the last years 🚀
