### ISSUE TITLE
TooltipWithBounds bug

### ISSUE THREAD

**Issue by terpimost** [airbnb/visx#767]
I think in TooltipWithBounds the line unstyled={unstyled} should be deleted because we checking styles in the style property
![image](https://user-images.githubusercontent.com/1903309/88241621-a5daf500-cc58-11ea-8060-6041d9501f14.png)

With that line if I use unstyled TooltipWithBounds no position will be set because inside ToolTip no styles will be set at all because they should be taken from TooltipWithBounds.

https://github.com/hshoff/vx/blob/8ede587c3cc47d56736bc58f99e3d8a94a1e0850/packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx#L53

**Comment by williaster** [comment]
@terpimost sorry for the delay, agree this is likely a bug! would happily review a PR 😁

**Comment by singhanurag05** [comment]
Hey @williaster may I remove the line? I'm new to open-source and I think I can do this!

**Comment by singhanurag05** [comment]
Should I just make the changes and create a pull request or am I supposed to do a yarn build?

**Comment by terpimost** [comment]
@singhanurag05 go ahead and remove the line

**Comment by singhanurag05** [comment]
Hi @terpimost can you please check PR #828 I did it.

**Comment by terpimost** [comment]
Its not up to me to check PRs in that repo, lets wait.

On October 1, 2020, Gary Kahn <notifications@github.com> wrote:
> Hi @terpimost <https://github.com/terpimost> can you please check PR

> #828 <https://github.com/airbnb/visx/pull/828> I did it.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/visx/issues/767#issuecomment-702187264>, or

unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAOQVTJ5HYOUZSFPMBDTGB3SISJCVANCNFSM4PFG73HA>.
