### ISSUE TITLE
Working example / sandpit using ChartContext

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#800]
I ahve started building my solution using the example based off #745 and using the ChartContext. It works nicely. Would be good to have a similar example showing best practice in one of the sandboxes.

Looking for a working example where the user can toggle between Bar, group, stacked and combo.

Like the approach taken in #745

I am particularly looking for an example with grouped stacked bars and tooltips. Will wait until Group is implemented in vx-xychart

**Comment by williaster** [comment]
as soon as we release the first version of `@visx/xy-chart` the example will link to a code sandbox. you can track the linked project.
