### ISSUE TITLE
chart tooltip trigger and position issue

### ISSUE THREAD

**Issue by Mikowhy-owl** [airbnb/visx#805]
I am using VX and d3 for my charts in project and I have problem with weird data when hovering on the dots.

![image](https://user-images.githubusercontent.com/24779051/93858008-ca386980-fcbb-11ea-864b-e2393b027da8.png)

This is basically how it looks - so I have data that is for lines and also data for this small dots on lines and everything works okay. The problem is that I don't now why but first and last dots on the first line doesn't show any data, even tooltip doesn't show. The second thing is that when I hover on the dot and move my mouse 1 mm to the left it shows previous dot in the weird position. Here is how it looks:

![image](https://user-images.githubusercontent.com/24779051/93858033-d290a480-fcbb-11ea-8a8d-5cb920c4bc58.png)

So basically it looks like when I move on the dot and get it's value and move mouse 1 mm to the left it shows previous value. 

Here is my code of the handletooltip function which basically manage showing the tooltip:

```
handleTooltip = ({ event, data, xScale, yScale }) => {
    let newData = [];

    data.contracts.map((item) => {
        const symbol = item.symbol;
        item.points.map((point, idx) => {
            item.points[idx] = { ...point, symbol };
        });

        newData = newData.concat(item.points);
    });

    newData = _.sortBy(newData, (x) => x.date);

    const { showTooltip, hideTooltip } = this.props;
    const { x } = localPoint(event);
    const x0 = xScale.invert(x);

    const index = bisectDate(newData, x0, 1);

    const d = newData[index - 1];

    if (this.state.tooltipValues !== yScale(ySelector(d))) {
        showTooltip({
            tooltipData: { ...d },
            tooltipLeft: x,
            tooltipTop: yScale(ySelector(d)),
        });
        this.setState({ tooltipValues: yScale(ySelector(d)) });
    } else {
        devLog("else");
        hideTooltip();
    }

    this.setState({
        verticalLineXValue: x,
    });
};
```

data.contracts.map just creates an array of all dots got from "contracts" element. If statement section is responsible for showing the data on the tooltip.

The vertical line on screenshots is just a line that goes with mouse when I move so it is easier to see on which position I am.

Data from the "contracts" object is fine because on previous version when I showed tooltips on all dots and I was not checking it by ` if (this.state.tooltipValues !== yScale(ySelector(d)))` data and tooltips were showing okay so there is definitely a problem in the code, not the data.

**Comment by williaster** [comment]
> first and last dots on the first line doesn't show any data
I'm not sure how you've set up `bisectDate`, but the index might be off by one on the edge values. For instance `const d = newData[index - 1]` might return nothing but `newData[index]` would. I think typically I pull out both values and choose whichever is closer (`x` distance wise, i.e., `x - xScale(xSelector(d))`) to the mouse event.

> when I hover on the dot and move my mouse 1 mm to the left it shows previous dot in the weird position
To me the y-value looks like it corresponds to the value to the left of where the tooltip is. Instead of using `tooltipLeft: x` from `localPoint`, maybe you could try setting `tooltipLeft: xScale(xSelector(d))` so it's guaranteed to match the `d` that you are showing tooltip data for?

**Comment by williaster** [comment]
going to close this as I think it's unrelated to `visx` itself. feel free to reopen if you think otherwise.
