### ISSUE TITLE
Chord: Ribbon edges overlap

### ISSUE THREAD

**Issue by Epskampie** [airbnb/visx#806]
When configuring the default Chord example like this: https://codesandbox.io/s/sparkling-lake-31ik4 
(only `dataMatrix` variable changed)

You'll see that the outside and inside of several ribbons overlap. I don't think this is intended.

![Selection_112](https://user-images.githubusercontent.com/1692043/93993731-61222600-fd8f-11ea-8f4a-17690f5bef0d.png)

**Comment by williaster** [comment]
Hey @Epskampie 👋  thanks for checking out `visx`. Do you mean the overlap or the ribbon "flipping" / "rotating"? 

I think in either case, it depends heavily on the data and is not unexpected. The [`d3-chord` readme](https://github.com/d3/d3-chord) has an example with overlapping + twisting chords:

![image](https://user-images.githubusercontent.com/4496521/94052869-6763d280-fd8e-11ea-8e8f-b6b9c680483a.png)

So this may be a d3 limitation. You could try tinkering with the [`sortGroups` / `sortGroups` / `sortSubgroups`](https://airbnb.io/visx/docs/chord#Chord_sortChords) props to see if that would make a difference for your dataset.

**Comment by Epskampie** [comment]
Thanks for the response. I only saw this project is a wrapper over D3 after I submitted the ticket. I think the overlapping/twisting is not an intuitive visualisation of the data, but I guess this is not the place to report it.
