### ISSUE TITLE
Event type checking prevents Enzyme's event simulation from working

### ISSUE THREAD

**Issue by srallen** [airbnb/visx#811]
Relavent package: visx/event

I have a custom constrain function defined for the `Zoom` component and I want to test the behavior to guarantee panning and zooming functions as expected. I use mocha and enzyme for tests and had a series of tests simulating events using enzyme's simulate function. Event simulation uses [`SyntheticEvent` objects](https://enzymejs.github.io/enzyme/docs/api/ReactWrapper/simulate.html#common-gotchas) which will fail the type checking here: https://github.com/airbnb/visx/blob/09ce16ff25384b756fb6f7298ad9e82002144c58/packages/visx-event/src/typeGuards.ts#L27-L32

I discovered this by upgrading vx from 0.0.192 to 0.0.199 and I'm not sure how to work around this. Given that the v1 was primarily a rebranding, I'm assuming that my tests fail with v1. Could the `SyntheticEvent` object be added to the allowed types?

**Comment by williaster** [comment]
Hey @srallen 👋  thanks for checking out `visx`. I'm not super familiar with the workings of enzyme's `SyntheticEvent`, but it [looks like](https://github.com/enzymejs/enzyme/blob/c5d5ee7da16f704d44f32ad3be55386c755295b0/packages/enzyme-adapter-react-16.2/src/ReactSixteenTwoAdapter.js#L326) it ultimately uses `react-dom`'s own [`TestUtils.Simulate`](https://reactjs.org/docs/test-utils.html#simulate) function. In the `react` docs they explicitly note:

> Note
> You will have to provide any **event property** that you’re using in your component (e.g. keyCode, which, etc…) as **React is not creating any of these for you**.

So I'm wondering if in your tests you could do something like `eventLayer.simulate('mouseup', { nativeEvent: new Event() })`? Not 100% sure that will work. @ljharb do you have any other thoughts? I think he'll recommend not using `simulate` 😛 

Side note: the `1.0.0` breaking changes are enumerated [here](https://github.com/airbnb/visx/releases/tag/v1.0.0), it's mostly `className` updates.

**Comment by srallen** [comment]
@williaster adding `{ nativeEvent: new Event() }` worked. Thanks for digging into it and the suggestion.

**Comment by ljharb** [comment]
Indeed i would; simulate doesn’t faithfully simulate anything. Adding the fake event object is the right solution here tho.
