### ISSUE TITLE
Is it possible to integrate with GSAP?

### ISSUE THREAD

**Issue by GilbertMizrahi** [airbnb/visx#812]
I just discovered visx and it looks very good. 
I have used D3 in the past. However, I have a pet project in which I will be using GSAP.

So, I wonder if I can combine visx with GSAP?

**Comment by hshoff** [comment]
Hi @GilbertMizrahi thanks for checking out visx. 

Yes this is definitely possible. Visx is just react so any animation library that works with react will work with visx. 

I haven't used GSAP with react/visx but here's a tutorial on how to use GSAP and react here: https://www.smashingmagazine.com/2020/09/animating-react-components-greensock/

Same patterns should apply to GSAP and visx.
