### ISSUE TITLE
AxisLeft: hideZero breaks ticks formatting

### ISSUE THREAD

**Issue by vfabioux** [airbnb/visx#815]
Hi,

There is a small bug caused by v0.0.199 (I can confirm it worked with v0.0.198 in my project), but I'm not sure how to fix it.

Setting hideZero to true on an AxisLeft makes the last tick ignore tickLabelProps.

Example:
https://codesandbox.io/s/heuristic-germain-5ywnv?file=/Example.tsx
Here the "90" tick is not formatted correctly.
This bug happens only when a 0 should be shown but hideZero is used to hide it.
If you remove hideZero (line 59) it will work again.
Same if you set temperatureScale domain's minimum to 10 (line 29) and keep hideZero.

**Comment by williaster** [comment]
Thanks for the report @vfabioux, I'll work on a fix for this shortly.
