### ISSUE TITLE
How performance can be improved?

### ISSUE THREAD

**Issue by vaasu070** [airbnb/visx#819]
Hi , I am using using `LinePath `element to draw lines . I am drawing 92 lines and each line is made of 12000 points. I should not miss any points because this is for data visualization purpose. This has one vertical line as well and it should be updating/advancing its position at the rate of 10 times per second . But this is not happening at such a rate , it is moving at 1 step per second. How can this be improved? 
                  
```
function DataAnalysisPlot({ width, height, data, time}) {

                    ....

                <svg
                    width={width}
                    height={height}>
                      ....
                <Group left={margin.left} top={margin.top}>

                {
               data.forEach((fo)=>
                    <LinePath
                    curve={curveLinear}
                    data={fo}
                    key={fo[0] && fo[0].id}
                    x={d => xScale(d.x)}
                    y={d => yScale(d.y)}
                    stroke={colors.Fused}
                    strokeWidth={1}
                    shapeRendering="optimizeSpeed"
                    clipPath="url(#BEV)"
                  />
                    )
                    }
               <line // timeline pointer
            x1={xScale(time)}
            x2={xScale(time)}
            y1={0}
            y2={yMax}
            stroke="red"
            strokeWidth={1.5}
            clipPath="url(#BEV)"
          />
        </Group>

              </svg>


           }
```
<img width="548" alt="svg" src="https://user-images.githubusercontent.com/33760706/94642051-b1096b80-0300-11eb-8f33-a0450288a039.PNG">

**Comment by hshoff** [comment]
Here are some thoughts, but it's hard to diagnose performance problems without diving into the code:

1. make sure you're using the [production build](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build) of react
1. make sure you're not doing expensive operations frequently. for example, every time the vertical line updates, does the whole chart re-render? Can use [`React.memo`](https://reactjs.org/docs/react-api.html#reactmemo) to wrap each LinePath so it only re-renders when props change. or [`useMemo()`](https://reactjs.org/docs/hooks-reference.html#usememo) when doing expensive operations on your data. 
1. [Profile](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) your components to identify where the problem spots are
1. React has a `<Profiler>` component that could also be helpful: https://reactjs.org/docs/profiler.html
1. 92 * 12,000 = +1M operations per data point, so make sure to avoid data iteration on interaction.
1. the vertical line that moves 10/s could be rendered to `<Portal>` https://reactjs.org/docs/portals.html
1. looking at the code sample above, there are inline function definitions as props which won't pass referential equality so they will always be re-rendered regardless of if any of the props have actually changed.

```diff
+ const x = d => xScale(d.x);
+ const y = d => yScale(d.y);

data.forEach((fo)=>
  <LinePath
    curve={curveLinear}
-   x={d => xScale(d.x)}
-   y={d => yScale(d.y)}
+   x={x}
+   y={y}
    stroke={colors.Fused}
    strokeWidth={1}
    shapeRendering="optimizeSpeed"
    clipPath="url(#BEV)"
  />
```
Generally, all of the performance best practices that apply in react apply in visx as well. Unfortunately, there is no one-size fits all answer to solve performance problems for all use cases. The best thing to do for perf problems is to measure, identify, and fix.  Hopefully some of the tools/tips above can help. If you identify bottlenecks in visx itself please followup with us and we can address it. 

Further reading:
- https://reactjs.org/docs/optimizing-performance.html
- https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render
- https://kentcdodds.com/blog/usememo-and-usecallback
- https://kentcdodds.com/blog/optimize-react-re-renders
- https://kentcdodds.com/blog/react-production-performance-monitoring
