### ISSUE TITLE
LinkHorizontalStep appears to be vertical

### ISSUE THREAD

**Issue by fdevillard** [airbnb/visx#820]
Hi there,

It looks like the `LinkHorizontalStep` is actually vertical. It turns out that it my project the `LinkHorizontalLine` is working well.

My guess is that the `LinkHorizontalStep` is missing a similar code from the `LinkHorizontalLine`:

```
  x = getY, // note this returns a y value
  y = getX, // note this returns a x value
```

Which is, in `LinkHorizontalStep`:

```
  x = getX,
  y = getY,
```

Cheers,
Florent

**Comment by williaster** [comment]
Thanks for reporting this! have a fix out.
