### ISSUE TITLE
history for my PR has been wiped

### ISSUE THREAD

**Issue by dagda1** [airbnb/visx#824]
This is not really a big thing but I just noticed that the history of my contribution has been wiped for the [Polygon file](https://github.com/airbnb/visx/commits/master/packages/visx-shape/src/shapes/Polygon.tsx).

This is [the original PR](https://github.com/airbnb/visx/pull/355).

It is good rep to have contributions into repos like this so that is a pity that it has been wiped.

**Comment by hshoff** [comment]
Hi Paul, sorry for this. This was an unfortunate limitation with GitHub and renames: https://github.com/isaacs/github/issues/900 

We'd be happy to accept another PR to restore history and we should add you to the contributors field of @visx/shape package.json as well

**Comment by dagda1** [comment]
absolutely no problem and thanks for the response.  it really is no big deal.

what would the PR be?

**Comment by hshoff** [comment]
I haven't tried this before but i think it would be 2 commits. One that removes the file and then one that adds it.

**Comment by dagda1** [comment]
@hshoff having thought about this, I think I'm being a bit daft.  I don't think I could live with myself if I create a PR that deleted something and readded it just so my name is there :).

I'll take a look at the issues and see if I can contribute something.

Thanks for your patience on this.
