### ISSUE TITLE
[demo/area] how to make the tooltip stay on-screen on mobile?

### ISSUE THREAD

**Issue by joshxyzhimself** [airbnb/visx#839]
![image](https://user-images.githubusercontent.com/60829711/94989164-4e84c980-05a5-11eb-8f7d-bbe46310d850.png)

This is on mobile and the label goes off-screen when I click the right-most side of the chart

Just curious about the right way to approach this :laughing:

**Comment by joshxyzhimself** [comment]
Possibly related to https://github.com/airbnb/visx/issues/466

**Comment by LethalPants** [comment]
This particular example doesn't use `TooltipWithBounds` which is why it goes off bounds.

**Comment by williaster** [comment]
gonna close this since it's solvable with `TooltipWithBounds` as shown in other examples (e.g., `/tooltip`)
