### ISSUE TITLE
How to change tooltip point to follow the curve rather than data index

### ISSUE THREAD

**Issue by nimabrownlee** [airbnb/visx#842]
I used an example in the gallery with a smaller dataset:
https://codesandbox.io/s/serverless-dawn-zuq85

If you look at it, you'll see that the tooltip point jumps between Y data. Is there a way to change the `handleTooltip` function so that the tooltip point follows the curve. No matter if the curve is linear, monotone, etc.

An example would be much appreciated.

**Comment by hshoff** [comment]
Hi @nimabrownlee, thanks for checking out visx. We don't have support for this out of the box, but it should be possible with a little math. Here are two examples that should help get started:

1. [Point-along-path](https://bl.ocks.org/mbostock/1705868)
1. [Closet point on path](https://bl.ocks.org/mbostock/1705868)

`<path>` nodes have a `getPointAtLength()` function which does as it says and returns the point at a length on the path. This point would be where you want the circle/tooltipLeft to be. Finding the length of the path given a mouse point is a little more involved but the [closestPoint()](https://bl.ocks.org/mbostock/1705868) function is a good start. 

Hope this helps!

**Comment by williaster** [comment]
Wanted to post [this medium post](https://devblog.classy.org/how-to-make-beautiful-graphs-with-vx-and-react-motion-6ffe7aecf6f3) which implemented this type of functionality with `vx` + `react-motion` (before `react-spring` came out I think). would be great to think about abstracting this into a reusable primitive.


![](https://miro.medium.com/max/982/1*bC5vMtpWz7qCFuSaD02lFg.gif)

**Comment by rishabhjaiz** [comment]
Was a support for this added?

**Comment by williaster** [comment]
@rishabhjaiz no it was not

**Comment by dclstn** [comment]
Bumping this
