### ISSUE TITLE
SortOrder on Pie

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#848]
Can someone please check the sortOrder on the pie. In the sandbox example. It looks like pieSort and PieSortValues render the same pie. I am looking at the outside pie.

I have pieSort={() => 1} and the pie is not rendered in alphabetical order. Maybe I am misreading the functionality.

If so how do I order by : labels or order by values?

**Comment by hshoff** [comment]
Sure here's an example demonstrating how to sort by labels/values: https://codesandbox.io/s/elastic-wind-7d9pw?file=/Example.tsx

sort by labels:

```jsx
<Pie
  data={browsers}
  pieValue={usage}
  pieSort={(a,b) => a.label.localeCompare(b.label)}
>
```

sort by values:
```jsx
<Pie
  data={letters}
  pieValue={frequency}
  pieSortValues={(a,b) => b - a}
>
```
