### ISSUE TITLE
[demo] all demos that use TooltipWithPortal have broken z-index

### ISSUE THREAD

**Issue by williaster** [airbnb/visx#850]
This is due to some styles in the re-branded demo site

`/tooltip`
![image](https://user-images.githubusercontent.com/4496521/95253087-be2bcc00-07d2-11eb-8229-b75a60f6bf15.png)

`/barstack`
![image](https://user-images.githubusercontent.com/4496521/95253219-f03d2e00-07d2-11eb-8c58-fefe8663cfd0.png)

cc @hshoff

**Comment by hshoff** [comment]
The fix is live: https://airbnb.io/visx/tooltip
