### ISSUE TITLE
d3-scale out of sync with typings

### ISSUE THREAD

**Issue by billyjanitsch** [airbnb/visx#855]
`@visx/scale` depends on `d3-scale@^3.0.1` and `@types/d3-scale@^2.1.1`. This means that a v3 scale passed to `@visx/axis` won't type-check correctly even though the runtime version is v3. It should depend on `@types/d3-scale@^3.0.0` instead.

https://github.com/airbnb/visx/blob/c0eb0b2aa5a8689e4b44d2642d56384a9a34ed30/packages/visx-scale/package.json#L33-L38

**Comment by williaster** [comment]
thanks for the bug report @billyjanitsch 🙏 happy to review a PR if anyone wants to take this on. @kristw does this sound reasonable to you?

**Comment by williaster** [comment]
side q: are you thinking of using `visx` for [`mixcreant`](https://github.com/billyjanitsch/mixcreant)? I've done some tinkering / thinking about cocktail vis so am excited to see what that turns out to be 📈 🍹 👀

**Comment by kristw** [comment]
Yes, this makes sense. 
The library `@types/d3-scale@3.x` was just released 2 days ago.
