### ISSUE TITLE
Question: use of hierarchy and stratify

### ISSUE THREAD

**Issue by PathToSharePoint** [airbnb/visx#876]
I have what I believe is a common use case, with a hierarchy described as a set of parent-child relationships:

```
data = [
  {child: "A", parent: ""},
  {child: "AA", parent: "A"},
  {child: "AB", parent: "A"},
  {child: "AC", parent: "A"},
  ...
]
```
I am trying to convert it to a hierarchy for a visx org chart. I found some examples from d3, but it seems that visx stratify doesn't work the same as d3 stratify. Could you point me to an example?

**Comment by williaster** [comment]
Hey @PathToSharePoint 👋  thanks for checking out `visx`. The `stratify` function that is exported in `@visx/hierarchy` is a convenience export and [exactly matches the one from `d3-hierarchy`](https://github.com/airbnb/visx/blob/master/packages/visx-hierarchy/src/index.ts#L11) so I would refer to the [`d3-hierarchy#stratify` docs](https://github.com/d3/d3-hierarchy#stratify).

The `[/treemap` demo](https://airbnb.io/visx/treemap ) uses `stratify` with the [`@visx/mock-data` Shakespeare dataset](https://github.com/airbnb/visx/blob/0cd702aa091a24a4c33282df4edfbcc41aadd5fa/packages/visx-mock-data/src/mocks/shakespeare.ts). Hope that helps.
