### ISSUE TITLE
Simple pie chart example

### ISSUE THREAD

**Issue by mihaildono** [airbnb/visx#879]
Hi, 
I am interested in using the library, however documentation is pretty scarce.
For example could you provide a more simple example for Pie chart?

Thanks in advance :)

**Comment by dzirg44** [comment]
agree. I also don't have a clue how to use `@visx/geo` with custom geo markers.

**Comment by hshoff** [comment]
Hi @mihaildono, thanks for checking out visx. 

Yes, this is an area we always hope to improve. Continue to open issues for specific packages/components/functions that require more attention (either with examples or API details) and we'll be happy to address or review PRs to improve. This will help us prioritize work in this area. 

I'm going to rename this issue to more accurately capture the first request to provide a more simple example for a pie chart. Then I'll open another issue to track @dzirg44's question about how to use @visx/geo with custom geo markers.

**Comment by hshoff** [comment]
Here's a more simple pie chart example: https://codesandbox.io/s/crazy-napier-tf4ed?file=/Example.tsx

```tsx
import React from "react";
import { Pie } from "@visx/shape";
import { Group } from "@visx/group";
import { scaleOrdinal } from "@visx/scale";
import { letterFrequency } from "@visx/mock-data";

const letters = letterFrequency.slice(0, 4);
const frequency = (d) => d.frequency;

const getLetterFrequencyColor = scaleOrdinal({
  domain: letters.map((l) => l.letter),
  range: [
    "rgba(93,30,91,1)",
    "rgba(93,30,91,0.8)",
    "rgba(93,30,91,0.6)",
    "rgba(93,30,91,0.4)"
  ]
});

const defaultMargin = { top: 20, right: 20, bottom: 20, left: 20 };

export type PieProps = {
  width: number;
  height: number;
  margin?: typeof defaultMargin;
};

export default function Example({
  width,
  height,
  margin = defaultMargin
}: PieProps) {
  const innerWidth = width - margin.left - margin.right;
  const innerHeight = height - margin.top - margin.bottom;
  const radius = Math.min(innerWidth, innerHeight) / 2;
  const centerY = innerHeight / 2;
  const centerX = innerWidth / 2;
  const top = centerY + margin.top;
  const left = centerX + margin.left;
  const pieSortValues = (a, b) => b - a;

  return (
    <svg width={width} height={height}>
      <Group top={top} left={left}>
        <Pie
          data={letters}
          pieValue={frequency}
          pieSortValues={pieSortValues}
          outerRadius={radius}
        >
          {(pie) => {
            return pie.arcs.map((arc, index) => {
              const { letter } = arc.data;
              const [centroidX, centroidY] = pie.path.centroid(arc);
              const hasSpaceForLabel = arc.endAngle - arc.startAngle >= 0.1;
              const arcPath = pie.path(arc);
              const arcFill = getLetterFrequencyColor(letter);
              return (
                <g key={`arc-${letter}-${index}`}>
                  <path d={arcPath} fill={arcFill} />
                  {hasSpaceForLabel && (
                    <text
                      x={centroidX}
                      y={centroidY}
                      dy=".33em"
                      fill="#ffffff"
                      fontSize={22}
                      textAnchor="middle"
                      pointerEvents="none"
                    >
                      {arc.data.letter}
                    </text>
                  )}
                </g>
              );
            });
          }}
        </Pie>
      </Group>
    </svg>
  );
}

```

**Comment by mcmanussean** [comment]
my frustration working with VisX is that all the examples are in typescript only. So not only is there little to no documentation in general but I need to reverse-engineer typescript to JSX first just to get a basic example to load. I'm not going to convert the entire project over to support typescript just to get the example code to work. very frustrating.

**Comment by williaster** [comment]
sorry for your frustration @mcmanussean. Airbnb's eng org has decided to go full in on TypeScript because of the major benefits it brings to being type safe and providing documentation for developers for free, so that's what `visx` uses and we don't have the bandwidth to write every example in JS as well. I'd highly recommend learning to at least read/understand TS even if you don't write it.

In harry's example above, the only TypeScript is `PieProps` which hopefully is quite readable and easy to remove.
