### ISSUE TITLE
Drag: initial position of a group

### ISSUE THREAD

**Issue by m0t0r** [airbnb/visx#894]
I am building an interactive chart which has a group of elements wrapped in a `<Group/>` which I need to drag over x axis.  In the demo for Drag (https://airbnb.io/visx/drag-i) circle's initial position is set via `cy={d.y}` and then dragging position is set via `transform={translate(${dx}, ${dy})}`, that's nice but I am struggling to find a solution for initial position of a group since `dx` and `dy` by default is `0` it resets the initial position but I need to drag that group from a specific `top` and  `left`. 

Do you have any tips how I could do that  or `@visx/drag` is not capable of that use case?

Thanks

**Comment by hshoff** [comment]
Hi @m0t0r, I think I get what you're going for but I'm not 100% sure. Does this example help? there's a Group with an initial position and you can drag the group around. https://codesandbox.io/s/initial-group-drag-vngb4?file=/Example.tsx

**Comment by m0t0r** [comment]
Hi @hshoff thanks for your reply and the example, unfortunately it's more complex in my case since I depend on the exact coordinates. I figured I would not be able to describe all details of my case in words, so I created a minimal demo here:  https://codesandbox.io/s/great-noether-u8kzj?file=/Example.tsx What I am struggling is to be able to define initial position of the group (timeline cursor), for example I need it to be at the last position by default. but since I take `dx` value, it's been rendered at `(0, 0)`

**Comment by m0t0r** [comment]
I will close this issue for now, I feel like it might be only my use case specific issue and I got some more ideas with a bit of additional math that looking like what I need. Thanks for the help!
