### ISSUE TITLE
Show labels on charts

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#896]
Is there any plan to add value labels to the charts?

I have been using the code form one of the old (vx) sandboxes and it seems to be affecting performance so was wondering if there is a batter way to do this.

      if (renderLabel && showLabels) {
          const Label = renderLabel({
            datum,
            index: i,
            labelProps: {
              key,
              ...labelProps,
              x: horizontal
                ? // ? minPosition + Math.abs(barLength)
                  minPosition + Math.max(0, barLength)
                : barPosition + barWidth / 2,
              y: horizontal
                ? barPosition + barWidth / 2
                : minPosition + Math.min(0, barLength),

              dx: horizontal ? "0.5em" : 0,
              dy: horizontal ? 0 : "-0.74em",
              textAnchor: horizontal ? "start" : "middle",
              verticalAnchor: horizontal ? "middle" : "end",
              width: horizontal ? null : barWidth,
            },
          });

**Comment by williaster** [comment]
Hi alan, I'm not sure where this code came from / what `renderLabel` does, but here are the [docs for `@visx/annotation`](https://airbnb.io/visx/docs/annotation). 

Depending on your needs you could also just render a `@visx/text` `Text` component (looks like the above code might do something like this).
