### ISSUE TITLE
Undocumented breaking change of <Axis> tickValues prop

### ISSUE THREAD

**Issue by aendra-rininsland** [airbnb/visx#901]
In 0.0.197, the `tickValues` prop of `<Axis>` would default to [`scale.domain()` if provided as a false-y value](https://github.com/airbnb/visx/blob/v0.0.197/packages/vx-axis/src/axis/Axis.tsx#L57). 

Now, [due to nullish coalescing](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/axis/Axis.tsx#L49-L51), a false-y value will throw a syntax error. 

This would've been a breaking change and should probably be documented as such.

**Comment by hshoff** [comment]
Oh no! Sorry to have missed that and thanks for letting us know. I'm sure that was an annoying bug to track down, we try to avoid those. 

We'll update the changelog to include this as a breaking change for v0.0.197

**Comment by aendrew** [comment]
No worries! 😄  In the process I noticed something we'd done wrong in one of our components that I might not noticed otherwise, so chutes and ladders I guess! 😂
