### ISSUE TITLE
feature(xychart): add ability to label any series point

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#903]
I have used the GlyphSeries to draw points and labels on line and bar charts and it works nicely. I have used them for both labels and Glyphs. Maybe taking a copy and renaming to LabelSeries would work quite nicely and offer most of the functionality required.

If so is there any plan to create a label / glyph series for stacked or grouped data?

**Comment by williaster** [comment]
Hey @alangrn 👋  thanks for the suggestion. I do plan on adding annotation support to the `@visx/xychart` package. My current plan is to actually build out better annotation components in `@visx/annotation`, which can then be used anywhere including `xychart` for any series type.

The `*Series` component implementation is interesting, this isn't how I was thinking about it, but I'll think about it some more 👍 . Added this issue to the `xychart` project tracker.
