### ISSUE TITLE
useEventEmitter TypeScript error

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#911]
Can you please check useEventEmitter in the hooks of visx-xyChart.

I get an error Typescript compile error- Expected 0 type arguments, but got 1

**Comment by williaster** [comment]
Hi @alangrn 👋  on `master` types compile fine for me locally and in CI using either `yarn build` or `yarn type:dts`.

I've mentioned this before to you but `@visx/xychart` is not yet published, so there are no guarantees for it working until then. You can follow #884 for updates on that.
