### ISSUE TITLE
ScaleLinear not matching types

### ISSUE THREAD

**Issue by OneCyrus** [airbnb/visx#914]
I'm struggling to get a working type for ScaleLinear with the axis component.

the following simplified example throws a type error.

```
      <AxisRight
        left={chartWidth}
        scale={scaleLinear<number>()}
        tickLabelProps={TICKET_LABEL_PROPS_AXIS}
        tickFormat={yTickFormat}
        hideAxisLine
        tickValues={ticks as any}
        stroke={AXIS_DEFAULT_CONFIGURATION.stroke}
        tickStroke={AXIS_DEFAULT_CONFIGURATION.tickStroke}
      />
```

![image](https://user-images.githubusercontent.com/7747800/98140710-0ae3ef00-1ec6-11eb-9b3f-186feab60d7f.png)

```
Type 'ScaleLinear<number, number, never>' is not assignable to type 'ValueOf<ScaleTypeToD3Scale<AxisScaleOutput, any, any>>'.
  Type 'ScaleLinear<number, number, never>' is missing the following properties from type 'ScalePoint<any>': round, padding, align, bandwidth, stepts(2322)
```

all visx components at latest version 1.1.0

**Comment by williaster** [comment]
Hey @OneCyrus 👋  thanks for checking out `visx`. Sorry for the issue, can you reproduce this in a codesandbox or similar?

I've trimmed down the `/axis` demo we have [here](https://codesandbox.io/s/awesome-sara-1wkeb?file=/Example.tsx:1707-1746) and it doesn't throw any errors, so it's tricky to debug further.

**Comment by OneCyrus** [comment]
I tried to reproduce but couldn't. so I checked further, and it seems to be some kind of sub dependency issue. on its own visx works fine. but combined with the other d3 libs and their @types there seem to be an issue with incompatible types. once I started to remove other d3 component types it started to work. I have a working combination now and I don't think there's anything you can do right now in this lib.
it seems to be a breaking change in the types which need to flow through the ecosystem properly until everything is working properly together again.
