### ISSUE TITLE
SplitLinePath: The segments are not split correctly

### ISSUE THREAD

**Issue by roxanagirdu** [airbnb/visx#920]
I am using SplitLinePath for a chart and when I am giving the segments array, the generated SVG points are not correct,  meaning that they are not split correctly and the first segment has points from the second segment and so on, so the segments are shifted a little bit. Did someone else had this issue or can help me?

**Comment by williaster** [comment]
Hey @roxanagirdu 👋  thanks for checking out `visx`. I've not experienced this issue before with `SplitLinePath`, but without a concrete example it's hard for us to debug further. 

Can you link to a codesandbox or equivalent so we can 👀 ?

**Comment by roxanagirdu** [comment]
Please find bellow an example. 
https://codesandbox.io/s/interesting-kepler-fpw96?file=/index.tsx

After the green line, it should start the second segment at index 240. But it does not do that.

**Comment by jtormey** [comment]
I've been using `visx` and have had a great experience so far, however I also have this problem. Here's another example (from my project) in case it helps with resolving the issue: [codesandbox](https://codesandbox.io/s/visx-normal-chart-wxpyo?file=/src/NormalChart.js).

You can see that where the line splits does not match up with either the axis line or the circle that indicate where `userValue` lies on the chart. Thanks!

**Comment by williaster** [comment]
Thanks for the sandboxes to reproduce! definitely seems like some type of bug. I'm not going to have the bandwidth to dig into this for a bit but would happily review a PR if anyone wants to 👀 🙏

**Comment by scottbasgaard** [comment]
Also running into this issue. Thanks for looking into this and will stay tuned!
