### ISSUE TITLE
Using @vx/brush with custom brush handles

### ISSUE THREAD

**Issue by JayWelsh** [airbnb/visx#922]
Is it possible to add "brush handles" to a component making use of @vx/brush?

For example, with something like Highcharts:

<img width="801" alt="Screenshot 2020-11-09 at 23 14 05" src="https://user-images.githubusercontent.com/14224459/98597332-8b995580-22e1-11eb-86be-14811996453b.png">

I feel like this would greatly enhance the functionality of @vx/brush

**Comment by peterwiebe** [comment]
Have you tried creating `<rect>`s and updating their positions based on the filtered data?

**Comment by timurmaio** [comment]
@hshoff @williaster what if we could pass components? We can pass components to customize ticks in axis, I think it would be cool to have the same functionality there. What do you think?

**Comment by Bad-Company** [comment]
Is there any updates on this issue?

**Comment by Stuhl** [comment]
The component isn't natively exposing a way to control the handlers but there is a workaround:

```
.visx-brush-handle-right, .visx-brush-handle-left {
  fill: hsla(0, 0%, 50%, 1);
  y: 0px;
}

.visx-brush-handle-right:hover, .visx-brush-handle-right:active {
  fill: hsla(0, 0%, 100%, 1);
}

.visx-brush-handle-left:hover, .visx-brush-handle-left:active {
  fill: hsla(0, 0%, 100%, 1);
}
```

Add this to your global css file and you will see a change. You can use `.visx-brush-handle-right` to style the right handle and `.visx-brush-handle-left` to style the left handle.

You can add the hover pseudo classes as a easy way to achieve hover state.
