### ISSUE TITLE
" This browser does not support ResizeObserver out of the box." on gallery

### ISSUE THREAD

**Issue by Y-Less** [airbnb/visx#923]
Viewing the gallery at https://airbnb.io/visx/gallery gives the above error on the latest version of Waterfox (2020.10).

**Comment by kristw** [comment]
Thank you for checking out `visx` in Waterfox. While we acknowledge the limitless possibilities of where `visx` might be used, due to our limited resource we have to focus our energy on the modern mainstream browsers.
