### ISSUE TITLE
Not display axis values

### ISSUE THREAD

**Issue by alangrn** [airbnb/visx#927]
I am trying to draw an axis (line) with no values.

What props do I need to set in BaseAxis? I have tried a few options and the values are still displayed.

**Comment by hshoff** [comment]
Can customize with the `tickComponent` prop:

```jsx
<AxisLeft
  scale={temperatureScale}
  tickComponent={() => null}
/>
```
https://codesandbox.io/s/determined-jennings-9sr95?file=/Example.tsx:2364-2428
