### ISSUE TITLE
CodeSandbox links in docs still link to hshoff/vx instead of airbnb/visx

### ISSUE THREAD

**Issue by omasback** [airbnb/visx#928]
for example:

`https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-brush`

should instead link to

`https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-brush`

**Comment by hshoff** [comment]
Hi @omasback, could you share a link where you're seeing this? The `Try it on CodeSandbox` button links to airbnb/visx here https://airbnb.io/visx/brush

**Comment by omasback** [comment]
oh shoot, you know what? I was looking at the old docs site `https://vx-demo.now.sh/`. I think it still comes up on google. Maybe redirect that to the new one?

**Comment by hshoff** [comment]
Going to close this for now.
