### ISSUE TITLE
feature(Brush): expose `updateBrush` to sync brush to chart

### ISSUE THREAD

**Issue by peterwiebe** [airbnb/visx#933]
I am creating a chart that includes a `<Brush/>` and want to add some additional button controls to set the X-axis at predetermined lengths. In this scenario, the X-axis is based on dates and the buttons would set the focused data based on last month/week/year/etc. It would be ideal to have the brush be consistent with what is shown in the chart.

One potential solution could be to expose `updateBrush` in **Brush.tsx** from **BaseBrush.tsx** so that a ref could be attached to `<Brush/>` that makes `updateBrush` available.

**Comment by peterwiebe** [comment]
@williaster I see you have a PR open around this already from #788

**Comment by peterwiebe** [comment]
Ah this is a duplicate of #577 😓 my bad

**Comment by williaster** [comment]
hey @peterwiebe sorry I should probably close #788 (EDIT: just did), it was more complex than anticipated. would happily review a PR if someone wants to take another shot at it 

cc #577
