### ISSUE TITLE
bug(network): string type is invalid for node/linkComponent

### ISSUE THREAD

**Issue by onlyreddy** [airbnb/visx#939]
Hi,

I started using @visx/network and tried to do customization for `nodeComponent `and `linkComponent`. But that's not working and the graph is unable to render. When I inspected and custom components are loaded in DOM.

Attached a sandbox demo [https://codesandbox.io/s/visxnetwork-customization-fuz8j?file=/Example.tsx](url)

Did I do anything wrong?. Please help me to render custom components

**Comment by williaster** [comment]
Hey @onlyreddy , I think the issue with your example is that `string`s are not valid components even tho they are typed that way (thus I updated the issue title accordingly, and we can leave it open until the `string` type is removed).

Here's a [demo](https://codesandbox.io/s/visxnetwork-customization-forked-ulsnt?file=/Example.tsx) of how you might customize them.

<img src="https://user-images.githubusercontent.com/4496521/99734363-8d98ac80-2a77-11eb-869b-f7221a353be1.png" width="250" />
