### ISSUE TITLE
How can brush selection be set programmatically?

### ISSUE THREAD

**Issue by JayWelsh** [airbnb/visx#941]
<img width="890" alt="Screenshot 2020-11-21 at 15 13 38" src="https://user-images.githubusercontent.com/14224459/99878179-3c6df180-2c0c-11eb-947f-9dbda03ec91d.png">

Is it possible to programmatically set the brush selection?

For example, if we let users click a "1 month" or "1 week" button, how would we get the brush to select just the last month or week of data?

Right now it seems like the only path to "set selection" is to use initialBrushPosition, but that doesn't seem viable in cases where we want users to be able to toggle between different brush position?

**Comment by JayWelsh** [comment]
For anyone else who comes across this, I managed to achieve the desired effect by updating the `initialBrushPosition` and then using a state variable for my brush container, which was the timestamp for when the `initialBrushPosition` is changed, and I set that timestamp to the `key` property of the `<Brush>` component:

```
<Brush
    key={timeboxTimestamp}
    xScale={brushDateScale}
    yScale={brushStockScale}
    width={xBrushMax}
    height={yBrushMax}
    margin={brushMargin}
    handleSize={16}
    resizeTriggerAreas={['left', 'right']}
    brushDirection="horizontal"
    initialBrushPosition={initialBrushPosition}
    onChange={onBrushChange}
    onClick={() => setFilteredStock(chartData)}
    selectedBoxStyle={selectedBrushStyle}
/>
```

```
const initialBrushPosition = useMemo(
    () => {
      let useChartData = chartData;
      if(timebox && (timeboxTimestamp !== lastTimeboxTimestamp)) {
        let rangeInHours = rangeToHours(timebox);
        if (rangeInHours) {
          let startTime = moment().subtract(rangeInHours, 'hours');
          useChartData = useChartData.filter((item) => {
            return moment(item.date).isAfter(startTime);
          });
        }
      }
      return {
        start: { x: brushDateScale(getDate(useChartData[0])) },
        end: { x: brushDateScale(getDate(useChartData[useChartData.length - 1])) },
      }
    },
    [brushDateScale, chartData, timebox, timeboxTimestamp],
);
```

**Comment by JayWelsh** [comment]
In essence, you can update the `initialBrushPosition` and then change the `key` property on the `Brush` to force a rerender with the updated `initialBrushPosition`

**Comment by williaster** [comment]
Also noting that #934 exposed the `updateBrush` method using an `innerRef` prop, and updated the `/brush` example to demonstrate how to use it.
