### ISSUE TITLE
Chrome throws error on using a "calc" string in dy of tspan

### ISSUE THREAD

**Issue by ConneXNL** [airbnb/visx#945]
@visx/text  is using a "calc" to set the "dy" of a tspan.

I am running Chrome (version 87.0.4280.66) and it throws an error whenever a "calc" is used for a "dy" attribute:

`Error: <tspan> attribute dy: Expected length, "calc(0 * -1em)"`
Firefox seems to throw a warning.

Is this issue known? Are there any workarounds?

**Comment by williaster** [comment]
Hey @ConneXNL 👋  thanks for checking out `visx`. 

No one has reported this issue before, do you have a sandbox to reproduce or can you elaborate on what props you are passing to `Text` when you see this error?

**Comment by ConneXNL** [comment]
Tried to extrict it and put it in codesandbox, but there for some reason it doesnt happen.

```
import { Text } from '@visx/text';
    <Text
        verticalAnchor={'end'}
        capHeight={'0.71em'}
        dx={0}
        dy={'0.25em'}
        fontFamily={'Arial'}
        scaleToFit={false}
        textAnchor={'middle'}
        x={16}
        lineHeight={'1em'}
        fontSize={10}
        y={18}
        color={'black'}
    >
        Jan 1, 19
    </Text>
```

I think for some reason the `reduce-css-calc` that is being used by @visx/text is not doing anything.

Because that package should change `calc(0 * -1em)` to `0em`

**Comment by williaster** [comment]
Closing this as it sounds like it was resolved. Feel free to reopen if that's not true.
