### ISSUE TITLE
Tooltip for multiline chart

### ISSUE THREAD

**Issue by olegKusov** [airbnb/visx#950]
How to make tooltip for multiline chart? Hover on series line must show circle and tooltip. Moreover, if there is not so much values, tooltip hover must have more area of activation.

**Comment by williaster** [comment]
Hey @olegKusov 👋  thanks for checking out `visx`. 

You can check out the [`areas` example](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-area?file=/Example.tsx) to see how you might do this. The example is for only one line, but includes all of the pieces you need. The general approach we use there is:

1) render an invisible `<rect />` to capture the pointer events (if you use a line, or area path, the pointer target size will be much smaller as you mention)
2) in the `onPointerMove` handler (or equivalent), convert the `Event`'s `x,y` coordinates to `svg` coordinates (we use the `@visx/event` helper `localPoint` to do this)
3) use `scale.invert` to map the svg coordinates to the _nearest_ value in your `scale`, e.g., a `Date` (`scales` typically convert an input e.g., `Date` to an svg coordinate, this does the opposite hence "`invert`")
4) _**for each of your `data` arrays**_ (note: the demo only does this for a single data array! but you will have multiple lines so you need to do it for each) use `bisect` from `d3-array` to find the nearest value in the `data` array to the `scale.invert` output
5) by now you should have the nearest `datum` for each `line`, and so you could invoke `showTooltip` with an object containing each point, something like `showTooltip({ tooltipData: { [lineId1]: nearestDatumForLineId1, [lineId2]: nearestDatumForLineId2, ... }, tooltipLeft, tooltipTop })`.

Hope that helps! Feel free to share your example when you get it working in case it's useful for others!

**Comment by Caedin** [comment]
I tried to do this, but it ended up not working for me specifically on this part:

`showTooltip({ tooltipData: { [lineId1]: nearestDatumForLineId1, [lineId2]: nearestDatumForLineId2, ... }, tooltipLeft, tooltipTop })`

The intention was to put a tooltip on each line, but with being limited to a single value for tooltipTop and tooltipLeft, I wasn't able to pass along the location for each line to go with each data point.

I can successfully get both data points and render all lines' data in a single tooltip spot, but I was really hopping to render the data floating over each line. 

It would be great if we could expand tooltipLeft and tooltipTop to accept more complicated data types, like tooltipData.
