### ISSUE TITLE
Question: How to use LinePath in a correct way?

### ISSUE THREAD

**Issue by SamYuan1990** [airbnb/visx#960]
Hi visx,

I want to use LinePath to draw a line.
I am start with BarGraph sample in read me and going to replace BarGraph with LinePath.
Is there any where can I have a tiny sample for LinePath?

as easy and tiny as 
https://github.com/airbnb/visx#usage

thanks and regard
sam

**Comment by sfrnqdr** [comment]
Here you go, Sir! :-)

https://gist.github.com/sfrnqdr/748da1da5b19a72bf56e62cfa799905a

BR,
Safran

**Comment by SamYuan1990** [comment]
> Here you go, Sir! :-)
> 
> https://gist.github.com/sfrnqdr/748da1da5b19a72bf56e62cfa799905a
> 
> BR,
> Safran

e.... Safran, I am located in BJ, and I can't access https://gist.github.com/sfrnqdr/748da1da5b19a72bf56e62cfa799905a ... do we have a fork on github.com?

**Comment by sfrnqdr** [comment]
No problem, than the quick 'n dirty way:

`
import React from 'react';
import { appleStock } from '@visx/mock-data';
import { Group } from '@visx/group';
import { scaleLinear, scaleTime } from '@visx/scale';
import { withParentSize } from '@visx/responsive'
import { LinePath } from '@visx/shape';
import { curveLinear } from '@visx/curve';
import { max, extent } from 'd3-array';
import { AxisLeft, AxisBottom } from "@visx/axis";

// We'll use some mock data from `@visx/mock-data` for this.
const data = appleStock

// Define the graph dimensions and margins
const width = 500;
const height = 500;
const margin = { top: 20, bottom: 20, left: 20, right: 20 };
const xAxisHeight = 20;

// Then we'll create some bounds
const xMax = width - margin.left - margin.right;
const yMax = height - margin.top - margin.bottom - xAxisHeight;

// We'll make some helpers to get at the data we want
const x = (d) => new Date(d.date);
const y = (d) => d.close;

// And then scale the graph by our data
const xScale = 
    scaleTime({
        range: [0, xMax],
        domain: extent(data, x),
})

const yScale = 
    scaleLinear({
        range: [yMax, 0],
        domain: [0, (max(data, y) || 0)],
        nice: true,
})

// Compose together the scale and accessor functions to get point functions
const compose = (scale, accessor) => data => scale(accessor(data));
const xCompose = compose(xScale, x);
const yCompose = compose(yScale, y);

const xPoint = d => xCompose(d) 
const yPoint = d => yCompose(d) 


// Finally we'll embed it all in an SVG
function LineGraph(props) {
  return (
    <svg width={width} height={height}>
        <Group 
            top={25} 
            left={65}>
        //AxisLeft 
            scale={yScale} 
            numTicks={4} />
        //AxisBottom
            top={yMax}
            left={0}
            scale={xScale} />
        <LinePath
            data={data}
            x={xPoint ?? 0}
            y={yPoint ?? 0}
            yScale={yScale}
            strokeWidth={1}
            stroke="red"
            curve={curveLinear} />
        </Group>
    </svg>
  );
}

export default (LineGraph)
` 
Will that be sufficient for you?

**Comment by SamYuan1990** [comment]
> No problem, than the quick 'n dirty way:
> 
> `
> import React from 'react';
> import { appleStock } from '@visx/mock-data';
> import { Group } from '@visx/group';
> import { scaleLinear, scaleTime } from '@visx/scale';
> import { withParentSize } from '@visx/responsive'
> import { LinePath } from '@visx/shape';
> import { curveLinear } from '@visx/curve';
> import { max, extent } from 'd3-array';
> import { AxisLeft, AxisBottom } from "@visx/axis";
> 
> // We'll use some mock data from `@visx/mock-data` for this.
> const data = appleStock
> 
> // Define the graph dimensions and margins
> const width = 500;
> const height = 500;
> const margin = { top: 20, bottom: 20, left: 20, right: 20 };
> const xAxisHeight = 20;
> 
> // Then we'll create some bounds
> const xMax = width - margin.left - margin.right;
> const yMax = height - margin.top - margin.bottom - xAxisHeight;
> 
> // We'll make some helpers to get at the data we want
> const x = (d) => new Date(d.date);
> const y = (d) => d.close;
> 
> // And then scale the graph by our data
> const xScale =
> scaleTime({
> range: [0, xMax],
> domain: extent(data, x),
> })
> 
> const yScale =
> scaleLinear({
> range: [yMax, 0],
> domain: [0, (max(data, y) || 0)],
> nice: true,
> })
> 
> // Compose together the scale and accessor functions to get point functions
> const compose = (scale, accessor) => data => scale(accessor(data));
> const xCompose = compose(xScale, x);
> const yCompose = compose(yScale, y);
> 
> const xPoint = d => xCompose(d)
> const yPoint = d => yCompose(d)
> 
> // Finally we'll embed it all in an SVG
> function LineGraph(props) {
> return (
> 
> 
> //AxisLeft
> scale={yScale}
> numTicks={4} />
> //AxisBottom
> top={yMax}
> left={0}
> scale={xScale} />
> <LinePath
> data={data}
> x={xPoint ?? 0}
> y={yPoint ?? 0}
> yScale={yScale}
> strokeWidth={1}
> stroke="red"
> curve={curveLinear} />
> 
> 
> );
> }
> 
> export default (LineGraph)
> `
> Will that be sufficient for you?

Appreciate, cool!, will try.

**Comment by williaster** [comment]
Thanks for sharing the example @sfrnqdr 👍 Wanted to note there are several https://airbnb.io/visx/gallery examples of `LinePath` such as [`/glyphs`](https://airbnb.io/visx/glyphs) that you could check out.

Going to close this for now, feel free to re-open if you have further questions.
