### ISSUE TITLE
Animated axis doesn't have dynamic keys

### ISSUE THREAD

**Issue by EfosaSO** [airbnb/visx#969]
Geeting a console warning when dynamically loading multiple animated axis:
`Warning: Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version. in AnimatedGridLines (created by GridRows)`

**Comment by williaster** [comment]
Hey @EfosaSO thanks for reporting this. Can you send a codesandbox to reproduce? 

The [`/axis` demo](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-axis) in the gallery does not have this issue, so I would suspect that the tick values that are being used somehow have duplicates themselves. But a demo will help confirm.

**Comment by EfosaSO** [comment]
Thanks @williaster for chiming in. I realise I was applying the keys incorrectly. Will close this now.
