### ISSUE TITLE
@visx/xychart not available from @visx/visx package

### ISSUE THREAD

**Issue by valtism** [airbnb/visx#974]
Hi guys. Super excited about `xychart` being out. 

Just noticed that since I'm using the `@visx/visx` import for prototyping that importing from `@visx/xychart` is not supported, and I have to manually install the `@visx/xychart` package.

Would like to be able to pull from the umbrella package like I can for the others. Thanks!

**Comment by williaster** [comment]
Hey @valtism thanks for checking out `xychart` and reporting this 🙏  This was an oversight by me and we should definitely add it. I'm a low on bandwidth over the holidays but happy to review a PR or can likely get to it next week!

**Comment by valtism** [comment]
Thanks! Zero rush on this feature, just a nice-to-have :)

**Comment by ShaneHudson** [comment]
I've picked this one up in PR https://github.com/airbnb/visx/pull/984 :+1:

**Comment by Christian-Sesta** [comment]
Curious how this issue is progressing?

**Comment by ShaneHudson** [comment]
I closed the PR I raised as it turned out to be a trickier change and I didn't have any spare time to pick up the extra changes. Sounds like @williaster knows how to handle it though.

**Comment by williaster** [comment]
Sorry just saw that #984 was closed. I can do this this week, it was slightly more complicated than we expected.
