### ISSUE TITLE
xychart README has ommision

### ISSUE THREAD

**Issue by hiroki0525** [airbnb/visx#975]
I found the ommision in xychart README. 
It should be added the statement `import Tooltip`, isn't it?
The example wasn't worked in my local environment.

```javascript
import {
  AnimatedAxis, // any of these can be non-animated equivalents
  AnimatedGrid,
  AnimatedLineSeries,
  Tooltip, // this statement is required.
  XYChart,
} from '@visx/xychart';

const data1 = [
  { x: '2020-01-01', y: 50 },
  { x: '2020-01-02', y: 10 },
  { x: '2020-01-03', y: 20 },
];
```

**Comment by ShaneHudson** [comment]
This is correct, I had the same issue with it.

**Comment by williaster** [comment]
@hiroki0525 thanks for reporting this, should be fixed now by @valtism's fix 🙏
