### ISSUE TITLE
[xychart] x/yscale config for zero/nice has no effect

### ISSUE THREAD

**Issue by Janpot** [airbnb/visx#986]
Noticed that `nice` and `zero` options for the `XYChart` scales don't have any effect. It's as if they are ignored:

```tsx
      <XYChart
        xScale={{ type: 'time' }}
        yScale={{ type: 'linear', zero: true, nice: true }}
        height={height}
      >
```

Can also be observed in this [modified example](https://codesandbox.io/s/stoic-cloud-mgspp?file=/ExampleControls.tsx:698-782)

**Comment by williaster** [comment]
Thanks again for reporting this and for the fix! 🙌

**Comment by Janpot** [comment]
@williaster Great. I also sort of need [custom Glyph for `Tooltip`](https://github.com/airbnb/visx/blob/1a051a96e8ee26db2c14ccf483cea373a68cad31/packages/visx-xychart/src/components/Tooltip.tsx#L256). Would you accept a PR that adds a renderprop to `Tooltip`? `renderGlyph` or something.

**Comment by williaster** [comment]
@Janpot yes! that was originally scoped for the MVP launch but didn't make the cut. I've created an issue to track #988, and would be happy to review a PR 👀
