### ISSUE TITLE
[xychart] can't set strokeWidth through verticalCrosshairStyle

### ISSUE THREAD

**Issue by Janpot** [airbnb/visx#990]
Setting `strokeWidth` to something greater than `1` in `verticalCrosshairStyle` on `XYChart` doesn't have any effect. Havent't tested it out, but from reviewing the code, I think [this `svg` width of `1`](https://github.com/airbnb/visx/blob/7f678d93aa3a17e74b934f678f118c5c72912365/packages/visx-xychart/src/components/Tooltip.tsx#L207) is causing the trouble here.

Can potentially be solved by adding CSS `overflow:visible` to that `svg` element.

**Comment by williaster** [comment]
thanks for reporting this @Janpot , I can prob get a fix out later today 👍
